Seagate/cortx-prvsnr

- srv/_modules/sync.py
> EOS-13567: setup-ees.yaml backup section files are not restored. (v2)

- api/python/provisioner/commands/deploy.py
- api/python/provisioner/commands/setup_provisioner.py
> Help string corrections for setup_provisioner

- srv/components/hare/files/cluster.cdf.tmpl
Signed-off-by: sradhanand.pati <sradhanand.pati@seagate.com>
> EOS-13558: Hare fix for different interface names in cluster (cortx-1.0)

- api/python/provisioner/commands/configure_setup.py
- api/python/provisioner/commands/setup_provisioner.py
> Fix single node setup using setup_singlenode API

- cli/src/replace_node/deploy-replacement
- srv/_modules/sync.py
> EOS-13567: setup-ees.yaml backup section files are not restored. (v3)

- api/python/provisioner/commands/__init__.py
> EOS-13629: Create csm-admin group on both nodes

- srv/components/uds/config.sls
- srv/components/uds/files/uds.service
> EOS-13397: Need to update uds service file once uds rpms get installed

- srv/components/hare/files/cluster.cdf.tmpl
> EOS-13651: Hare CDF formatting causing iostack-ha to fail

- cli/buildrpm.sh
- cli/cortx-prvsnr-cli.spec
> Improvise ssh key encryption

- api/python/provisioner/__main__.py
- api/python/provisioner/api_spec.yaml
- api/python/provisioner/commands/auto_deploy.py
- api/python/provisioner/commands/configure_setup.py
- api/python/provisioner/commands/get_setup_info.py
- api/python/provisioner/commands/replace_node.py
- api/python/provisioner/commands/setup_jbod.py
- api/python/provisioner/commands/setup_provisioner.py
- api/python/provisioner/config.py
- improved default configuration for for setup commands:
- file logging is turned on by default
- rsyslog logging is turned off by default (fix for EOS-13584)
> [EOS-13584][EOS-13228] Improves default file logging for setup cmds

- cli/buildrpm.sh
- srv/_modules/sync.py
> EOS-13679: ssh config file not found: /root/.ssh/config

- srv/components/system/logrotate/config.sls
> EOS-13687: Use grains to check if server is physical or vm

- srv/components/ha/iostack-ha/files/ha-params.tmpl
> EOS-13356: HA: support different data nw-interface names on nodes

- srv/components/misc_pkgs/rabbitmq/config/base.sls
> EOS-13250: Start-Stop rabbitmq service instead of restart.

- cli/cortx-prvsnr-cli.spec
This reverts commit 185ffdf6fc2c34f6c35311416b7e2bd826c765b0.
> Revert "EOS-13679: ssh config file not found: /root/.ssh/config (#526)"

- api/python/provisioner/__main__.py
- api/python/provisioner/api_spec.yaml
- api/python/provisioner/commands/auto_deploy.py
- api/python/provisioner/commands/configure_setup.py
- api/python/provisioner/commands/get_setup_info.py
- api/python/provisioner/commands/replace_node.py
- api/python/provisioner/commands/setup_jbod.py
- api/python/provisioner/commands/setup_provisioner.py
- api/python/provisioner/config.py
Reverts Seagate/cortx-prvsnr#521
> Revert "[EOS-13584][EOS-13228] Improves default file logging for setup cmds"

- cli/src/deploy
- cli/src/replace_node/deploy-replacement
- srv/_modules/sync.py
- srv/components/ha/iostack-ha/init.sls
> EOS-13698: M5: hare-consul-agent-c1.service could not be found

- api/python/provisioner/commands/__init__.py
> EOS-13772: PATH updated for admin user access

- api/python/provisioner/__metadata__.py
- api/python/provisioner/commands/replace_node.py
- api/python/provisioner/commands/setup_provisioner.py
- api/python/provisioner/config.py
- srv/components/defaults.yaml
- adds support for separate remotely mounted ISO files for 3rd party dependencies (deps bundle url)
- adds support of non local source of provisioner setup for replace node logic
> [EOS-13651][EOS-13686] improves rpm based setup support

- cli/src/factory_ops/unboxing/config_update
- cli/src/factory_ops/unboxing/init
> EOS-13740: Remove target_build from release pillar during unboxing.

- srv/components/defaults.yaml
> HF: default.yaml malformed JINJA dict list

- Cortx-ProvisionerQuickstartGuide.md
- api/python/provisioner/__main__.py
- api/python/provisioner/__metadata__.py
- api/python/provisioner/api_spec.yaml
- api/python/provisioner/commands/__init__.py
- api/python/provisioner/commands/auto_deploy.py
- api/python/provisioner/commands/configure_setup.py
- api/python/provisioner/commands/get_setup_info.py
- api/python/provisioner/commands/replace_node.py
- api/python/provisioner/commands/setup_jbod.py
- api/python/provisioner/commands/setup_provisioner.py
- api/python/provisioner/config.py
- api/python/provisioner/inputs.py
- api/python/provisioner/srv/salt/provisioner/configure_salt_master.sls
- cli/src/deploy
- cli/src/replace_node/deploy-replacement
- pillar/components/samples/generic_config.ini
- pillar/components/samples/template.yml
- pillar/components/storage_enclosure.sls
- srv/_modules/sync.py
- srv/components/defaults.yaml
- srv/components/ha/haproxy/files/haproxy.cfg
- srv/components/ha/iostack-ha/init.sls
> pre-cortx-1.0 -> cortx-1.0: 30092020

- srv/components/sspl/install.sls
> Disable prepare dependencies in sspl:install

- srv/components/hare/install.sls
> Disable prepare dependencies in hare:install

- api/python/provisioner/config.py
- api/python/provisioner/srv/pillar/groups/all/release.sls
- pillar/components/release.sls
Reverts Seagate/cortx-prvsnr#556. After discussion with @andkononykhin2 we decided to revert this PR for the additional testing
> Revert "[WIP][EOS-12334]-ISO files with updates should be located outside installation directory"

- api/python/provisioner/commands/setup_provisioner.py
- api/python/provisioner/utils.py
- srv/components/misc_pkgs/openldap/replication/teardown.sls
> [EOS-12076] Fix yaml dump issue with iso based deployments

- srv/components/s3server/backup.sls
- srv/components/s3server/config.sls
- srv/components/s3server/refresh_config.sls
- srv/components/s3server/restore.sls
- srv/components/s3server/sanity_check.sls
- srv/components/s3server/sync.sls
- srv/components/s3server/teardown.sls
> EOS-13852: Change in root_node for S3 setup.yaml

- api/python/provisioner/srv/salt/provisioner/install/local.sls
> EOS-13771: Fixes vanishing generated_configs mystery

- api/python/provisioner/srv/salt/firewall/stop.sls
> EOS-13072: Firewall to be disabled during bootstrap

- cli/src/deploy-vm
- cli/src/factory_ops/unboxing/init
- srv/components/ha/haproxy/files/haproxy.cfg
- srv/components/ha/haproxy/init.sls
- srv/components/s3server/start.sls
Signed-off-by: sradhanand.pati <sradhanand.pati@seagate.com>
> EOS-13953:s3server deployment failed

- srv/components/system/firewall/config.sls
> EOS-13807: Update UDS-related firewall rules

- api/python/provisioner/commands/setup_provisioner.py
- api/python/provisioner/srv/salt/saltstack/salt_master/ensure_running.sls
- srv/components/provisioner/salt_minion/files/minion
- hardens logic of salt-master restart during setup
- fixes #590
> EOS-14019: Ensure salt ready after restart

- srv/components/system/logrotate/files/etc/logrotate_hw.d/provisioner
> EOS-9758: Software upgrade fails when /var is full

- cli/src/factory_ops/boxing/prov_tasks
> EOS-13954: Use uuid to generate one time password for cortxub user.

- srv/components/misc_pkgs/openldap/config/base.sls
- srv/components/misc_pkgs/openldap/replication/config.sls
- srv/components/misc_pkgs/openldap/replication/sanity_check.sls
- srv/components/misc_pkgs/openldap/sanity_check.sls
> EOS-13884: ldap password is appearing in clear text in journal logs

- api/python/provisioner/salt.py
- api/python/provisioner/salt_minion.py
> [EOS-13921] raises an error in case no connection to minion

- api/python/provisioner/commands/setup_provisioner.py
- api/python/provisioner/utils.py
- cli/src/replace_node/deploy-replacement
- srv/components/sspl/health_view/config/generate.sls
> EOS-14113, EOS-14119: Storage Enclosure Health view issue

- api/python/provisioner/commands/__init__.py
- api/python/setup.py
- srv/components/misc_pkgs/eosupdate/repo/sanity_check.sls
> [EOS-14096][GA] sw update hardening

- srv/components/system/logrotate/config.sls
- srv/components/system/logrotate/files/etc/logrotate.conf
- srv/components/system/logrotate/files/etc/logrotate_vm.conf
> EOS-9758: Set logrotate cronjob to hourly

- cli/src/replace_node/deploy-replacement
> EOS-14228: Deploy_replacement fails at 'Applying File Restore States'

- cli/src/factory_ops/boxing/prov_tasks
- cli/src/factory_ops/unboxing/config_update
- cli/src/factory_ops/unboxing/pre_unbox
1.  Remove repo files with seagate or saltstack domain references
2. Skip disabling subscription manager if the system is not RedHat
3. Skip removing the repo file if it's pointing to locally mounted iso
> EOS-14210: Box/unbox - Improvise logic to cleanup factory references

- cli/src/factory_ops/unboxing/config_update
- cli/src/factory_ops/unboxing/init
> EOS-14120: SSPL stuck in stopped state on Node-2 after unboxing

- api/python/provisioner/commands/setup_provisioner.py
- api/python/provisioner/salt.py
- api/python/provisioner/srv/salt/provisioner/api/install.sls
> [EOS-14076] Revert "Revert "fixes gluster configuration for node replace case"

- api/python/provisioner/inputs.py
- api/python/provisioner/utils.py
- test/api/python/provisioner/test_inputs.py
Signed-off-by: Sudarshana Babar <sudarshana.babar@seagate.com>
> EOS-12439: Implemented 8 unit tests for inputs.py classmethods.

- cli/src/replace_node/deploy-replacement
----------------------------------------------------------------------
EOS-14263: Node replacement on updated setup
resets to Factory default release version
> EOS-14263: Node replacement on updated setup fails

- api/python/provisioner/commands/deploy_dual.py
- api/python/provisioner/commands/deploy_vm.py
- cli/src/destroy
- cli/src/destroy-vm
- srv/components/misc_pkgs/consul/config.sls
- srv/components/misc_pkgs/consul/install.sls
- srv/components/misc_pkgs/consul/prepare.sls
- srv/components/misc_pkgs/consul/sanity_check.sls
- srv/components/misc_pkgs/consul/teardown.sls
- srv/components/sspl/config/commons.sls
> EOS-14262: Enable Consul Installation & softlink creation

- cli/src/cortx-prereqs.sh
- srv/components/provisioner/config.sls
> fix deployment issues

- srv/components/system/storage/config.sls
> EOS-14183: Add tag to avoid VG duplication

- srv/components/hare/install.sls
- srv/components/system/teardown.sls
> #646: Remove jq from teardown

- srv/_modules/sspl.py
- srv/components/sspl/config/sspl.sls
- srv/components/sspl/health_view/config/generate.sls
> EOS-14376: Correct HealthMap generation sequence.

- srv/components/system/storage/config.sls
> EOS-14183: Workaround for https://github.com/saltstack/salt/issues/58747

- api/python/provisioner/commands/deploy.py
- api/python/provisioner/commands/deploy_dual.py
- cli/src/deploy
- srv/components/motr/config.sls
- srv/components/motr/refresh_config.sls
- srv/components/motr/sanity_check.sls
- srv/components/motr/teardown.sls
> EOS-14131: Replace core to motr in setup.yaml

- srv/components/misc_pkgs/rabbitmq/config/base.sls
- srv/components/misc_pkgs/rabbitmq/files/rabbitmq-server
- srv/components/system/logrotate/config.sls
- srv/components/system/logrotate/files/etc/logrotate.conf
- srv/components/system/logrotate/files/etc/logrotate_vm.conf
> EOS-14392: Update permissions for rabbitmq rotated files

- api/python/provisioner/commands/setup_provisioner.py
- cli/src/factory_ops/unboxing/init
- cli/src/factory_ops/unboxing/pre_unbox
-disable internal function calls
-enable replace_node API call
> [EOS-13909] Update unboxing logic to support active-active Provisioner configuration

- cli/src/replace_node/deploy-replacement
> EOS-14360: UDS and CSM admin user changes for M5

- cli/src/virtual_appliance/bootstrap.sh
> Fix bootstrap file for OVA

- cli/src/factory_ops/boxing/init
- cli/src/factory_ops/boxing/prov_tasks
- srv/components/system/network/mgmt/service_port/init.sls
> EOS-14140: Factory (manufacturing) install

- api/python/provisioner/commands/__init__.py
> [EOS-14636] restart of salt minion should be done at the end

- api/python/provisioner/hare.py
- cli/src/csm_admin_user.py
- srv/components/misc_pkgs/consul/install.sls
- srv/components/sspl/teardown/commons.sls
> EOS-14382: Remove hare consul symlink

- pillar/components/samples/config.ini
- pillar/components/samples/dualnode.cluster.sls
- pillar/components/samples/generic_config.ini
- pillar/components/samples/jbod_config.ini
- pillar/components/samples/singlenode.cluster.sls
- pillar/components/samples/template.yml
> EOS-14142: Remove any password entries in pillar

- srv/components/system/network/mgmt/service_port/init.sls
> Boxing: Set jinja variable before using it.

- srv/components/ha/haproxy/files/haproxy.cfg
> EOS-14650:Haproxy failing for jinja error

- api/python/provisioner/commands/replace_node.py
- api/python/provisioner/commands/setup_provisioner.py
- api/python/provisioner/config.py
- api/python/provisioner/errors.py
- cli/src/factory_ops/boxing/init
- cli/src/factory_ops/boxing/prov_tasks
- cli/src/factory_ops/boxing/shutdown
- cli/src/factory_ops/unboxing/config_update
- cli/src/factory_ops/unboxing/init
- cli/src/factory_ops/unboxing/pre_unbox
- cli/src/factory_ops/unboxing/system_check
- srv/components/csm/prepare.sls
- srv/components/system/prepare.sls
> [EOS-14289][EOS-14321][EOS-13909] Unboxing changes, ported from Beta

- srv/components/ha/corosync-pacemaker/config/stonith.sls
> EOS-14462:Stonith default action should be off

- cli/src/common_utils/functions.sh
- cli/src/factory_ops/boxing/prov_tasks
- cli/src/factory_ops/unboxing/config_update
- cli/src/factory_ops/unboxing/init
- cli/src/factory_ops/unboxing/pre_unbox
- cli/src/factory_ops/unboxing/system_check
- srv/components/system/prepare.sls
The patch has following changes:
1. Port changes from Raytheon unboxing session to Beta.
2. Cleanup Seagate URLs
3. Call healthview configuration at the end of unboxing.
4. Remove functions.sh dependency from unboxing.
> EOS-14185 and other misc boxing/unboxing fixes.

- api/python/provisioner/commands/__init__.py
- api/python/provisioner/commands/deploy.py
- api/python/provisioner/commands/deploy_dual.py
- api/python/provisioner/commands/deploy_vm.py
- cli/src/deploy
- cli/src/deploy-vm
- cli/src/destroy
- cli/src/destroy-vm
- cli/src/replace_node/deploy-replacement
- srv/components/ha/ctrlstack-ha/init.sls
- test/api/python/provisioner/test_commands.py
> EOS-14470: Flip deploy sequence for CSM-UDS

- cli/src/cortx_prep.sh
> cortx-prep-fix: fix issues

- srv/components/system/network/mgmt/service_port/init.sls
> EOS-14795: Define Jinja variable before using it.

- cli/src/factory_ops/boxing/shutdown
> Boxing: Don't use Salt command to shutdown the nodes

- srv/components/system/config/pillar_encrypt.sls
> cortx-prep-fix: Skip cryptography install as it gets installed through cortx-py-utils

- cli/src/factory_ops/boxing/prov_tasks
- cli/src/factory_ops/boxing/shutdown
Changes in this patch:
1. Don't stop Salt services during Gluster unmount
2. Keep using Salt commands to shutdown the nodes in async mode.
> EOS-14814: Don't stop salt services during boxing.

- srv/_modules/lyveutil.py
- srv/components/system/config/pillar_encrypt.sls
> EOS-14830: Issue with cryptography module fixed

- cli/src/common_utils/lr-serial-number
- cli/src/factory_ops/boxing/init
> Boxing: Use absolute path for ls-setial-number script.

- srv/components/sspl/install.sls
> EOS-14956: Remove repo creation part (prepare) from SSPL install sls.

- api/python/provisioner/commands/__init__.py
- api/python/provisioner/errors.py
- api/python/provisioner/salt.py
- fixes regression in get_result routine
- disables the logic that fails sw update in case the same update release is being asked to be configured: for now it would just warns and removes already configured one
> [EOS-14884] SW Update fixes

- srv/components/system/firewall/config.sls
> EOS-14841: Remove trusted sources and allow access only through interface

- test/README.md
Fix spell warnings, improve formatting, add table of contents.
> Fix/improve formatting in test/README.md

- pillar/components/commons.sls
- pillar/components/samples/template.yml
- srv/components/defaults.yaml
> EOS-14923: Remove default URLs from commons pillar

- cli/src/factory_ops/unboxing/config_update
> EOS-14960: Fix typos in variable names in unboxing.

- srv/components/sspl/install.sls
> Remove prepare sls dependency from install sls

- srv/components/system/logrotate/files/etc/logrotate.conf
- srv/components/system/logrotate/files/etc/logrotate_hw.d/provisioner
- srv/components/system/logrotate/files/etc/logrotate_vm.conf
- srv/components/system/logrotate/files/etc/logrotate_vm.d/provisioner
> EOS-14839: add dateformat and fix provisioner logrotate error

- srv/components/system/network/config.sls
- srv/components/system/network/prepare.sls
> LRL-851: FQDN to be retained in node replacement scenario

- cli/src/factory_ops/unboxing/pre_unbox
> EOS-14964: Unboxing: Add the missing quote to the parameter to mv command.

- api/python/setup.py
> Fix the Salt version for Provisioner API

- srv/components/system/firewall/config.sls
> [EOS-14991] Block rabbitmq ports on management and data networks

- cli/src/common_utils/lr-serial-number
- cli/src/common_utils/utility_scripts.sh
- cli/src/factory_ops/boxing/init
- cli/src/factory_ops/boxing/prov_tasks
- cli/src/factory_ops/boxing/shutdown
- cli/src/factory_ops/unboxing/config_update
- cli/src/factory_ops/unboxing/pre_unbox
Changes in this patch:
1. Include manifest file generation as part of boxing
2. Make boxing idempotent
3. Add more loging information in during boxing.
> EOS-14875: Include manifest file generation as part of boxing

- cli/src/common_utils/utility_scripts.sh
- cli/src/factory_ops/boxing/prov_tasks
- cli/src/factory_ops/unboxing/system_check
> Unboxing fix: Use salt to fetch data

- cli/src/common_utils/utility_scripts.sh
- cli/src/factory_ops/unboxing/system_check
This reverts commit 8f34b8f82ebce87241892a0356e3b92ac514ab27.
> EOS-15097: Revert "Unboxing fix: Use salt to fetch data (#734)"

- cli/src/common_utils/utility_scripts.sh
> Patch to fix codacy warning for PR# 737

- cli/src/common_utils/utility_scripts.sh
- cli/src/factory_ops/unboxing/system_check
This reverts commit 8f34b8f82ebce87241892a0356e3b92ac514ab27.
> EOS-15097: Revert "Unboxing fix: Use salt to fetch data (#734)" (#736)

- cli/src/factory_ops/unboxing/init
> EOS-15100: Unmaintenance the HCTL cluster post configuration update.

- cli/src/factory_ops/unboxing/init
> EOS-15140: Bring cluster out of maintenance mode before SSPL and CSM config

- srv/components/ha/corosync-pacemaker/config/cluster_ip.sls
- srv/components/ha/corosync-pacemaker/config/mgmt_vip.sls
I have no ability to update @AshwiniS-Borse local branch (it was made as a fork from `pre-cortx-1.0`). I created a separate branch for that but keeping history from @AshwiniS-Borse. Updated it by my changes.
> [EOS-15043] - Assign prefix/subnet mask to cluster-ip and mgmt-vip

- cli/src/cortx_prep.sh
- cli/src/factory_ops/unboxing/init
> EOS-15156: Add check to remove only remote build url

- srv/components/system/network/prepare.sls
> EOS-15141: Restart dhclient after killing it

- cli/src/factory_ops/unboxing/init
> EOS-15160: start haproxy after csm config in unboxing

- pillar/components/cluster.sls
> cluster.sls has wrong entry for mgmt_nw:public_ip_addr

- api/python/provisioner/commands/replace_node.py
- cli/src/factory_ops/unboxing/init
> EOS-15197: Improve profile dir reference picker logic

- devops/rpms/cortx-prvsnr.spec
> EOS-15184:Support bundle generation failed for provisioner and health_map

- api/python/provisioner/config.py
> EOS-14811: Avoid duplication of cluster_id during auto_deploy

- pillar/components/cluster.sls
- pillar/components/samples/dualnode.cluster.sls
- pillar/components/samples/singlenode.cluster.sls
- pillar/components/samples/template.yml
- srv/components/csm/files/ha-params.tmpl
- srv/components/system/network/prepare.sls
> EOS-15292: Updating vips failed during Unboxing in DHCP environment

- srv/components/system/network/prepare.sls
> Improvise dhclient command in network.prepare

- cli/src/factory_ops/unboxing/init
- cli/src/factory_ops/unboxing/network/public_data
- cli/src/factory_ops/unboxing/network/public_mgmt
> EOS-15312: Typo in Public network interface unboxing

- srv/components/system/network/init.sls
- srv/components/system/network/mgmt/public/init.sls
- srv/components/system/network/prepare.sls
> Improvise dhclient command and add HW addr in management interface

- cli/src/replace_node/deploy-replacement
> EOS-14767: Update replacement states execution sequence

- api/python/provisioner/commands/auto_deploy.py
- api/python/provisioner/commands/check.py
- api/python/provisioner/commands/replace_node.py
- api/python/provisioner/config.py
- api/python/provisioner/errors.py
1. Added both pre-deploy and post-deploy checks. Works as expected (positive and exception scenarios). 
2. For both validations, raising Exception and breaking the flow right there.
> EOS-14136: DecisionMaker class for factory deployment

- cli/src/factory_ops/unboxing/init
- cli/src/factory_ops/unboxing/system_check
- Added below pre-checks in unboxing
- IP addresses for public data interfaces are set
- BMC accessibility from both servers
- Server-A and Server-B can access (ping) Controller-A and
Controller-B on the enclosure
Signed-off-by: Sanjog Vikram Naik <sanjog.naik@seagate.com>
> EOS-14135: add unboxing pre-flight checks

- api/python/provisioner/commands/auto_deploy.py
- api/python/provisioner/commands/check.py
- api/python/provisioner/config.py
> changing multipath as a new check and adding Dynamic imports

- cli/src/factory_ops/boxing/init
- cli/src/factory_ops/boxing/prov_tasks
- srv/components/system/config/hosts.sls
> EOS-15458: Provisioner overwrites the hosts file during deployment of system component

- api/python/provisioner/commands/auto_deploy.py
- api/python/provisioner/commands/check.py
- api/python/provisioner/commands/replace_node.py
> Updated BMC check and fix flake8 issues

- srv/components/system/network/files/dns_check.sh
- srv/components/system/network/prepare.sls
- adds limited awaiting for DNS to set up after dhclient restart
> adds dns validation step after dhclient restart

- api/python/provisioner/log.py
hardens logging errors processing logic
> [EOS-15450] fixes possible infinite loop in logging

- cli/src/replace_node/deploy-replacement
update provisioner and related config files ones update repository is available on a replacement node
> [EOS-15403] update provisioner at deploy-replacement

- api/python/provisioner/commands/__init__.py
- api/python/provisioner/commands/auto_deploy.py
- api/python/provisioner/commands/check.py
- api/python/provisioner/commands/replace_node.py
- api/python/provisioner/config.py
- api/python/provisioner/errors.py
- cli/src/factory_ops/unboxing/init
- cli/src/factory_ops/unboxing/system_check
Signed-off-by: mazinamdar mazhar.inamdar@seagate.com
> Pre cortx 1.0 validation

- cli/src/factory_ops/unboxing/config_update
- cli/src/factory_ops/unboxing/network/public_mgmt
> EOS-15411: resolv.conf update missed during unboxing

- cli/src/common_utils/utility_scripts.sh
the change is valid for pcs version 0.9.169
> updates ensure_healthy_cluster to newer pcs status output format

- srv/components/misc_pkgs/openldap/config/base.sls
- srv/components/misc_pkgs/openldap/files/resultssizelimit.ldif
- srv/components/misc_pkgs/openldap/prepare.sls
> EOS-15116:IAM user: CSM CLI/GUI only list 500 users

- srv/components/ha/haproxy/files/haproxy.cfg
- srv/components/s3server/teardown.sls
> EOS-13281:Update haproxy ports

- Cortx-ProvisionerQuickstartGuide.md
Updated CentOS, Kernel, and Mellanox versions
Signed-off-by: Saumya Sunder <saumya.sunder@seagate.com>
> Updated CentOS, Kernel, and Mellanox versions

- cli/src/common_utils/utility_scripts.sh
> EOS-15612: Improve user experince of the unboxing logging.

- srv/_modules/gluster.py
- srv/components/system/storage/glusterfs/teardown/heal_cluster.sls
salt-call gluster.add_brick <volume> <brick>
salt-call gluster.remove_brick <volume> <brick>
salt-call gluster.is_brick_present <volume> <brick>
salt-call gluster.remove_peer <hostname>
Heal cluster: remove nodes which are not pingable.
salt 'srvnode-1' state.apply components.system.storage.glusterfs.teardown.heal_cluster
> [EOS-15852][EOS-15941] salt modules to add, remove volume ,detach node and heal cluster

- pillar/components/csm.sls
- pillar/top.sls
* EOS-15665: Generate passwd for csm user
* Added csm entry to pillar top.sls
> EOS-15665: For SMS2

- cli/src/factory_ops/unboxing/init
> EOS-16027: Restart all services once CSM and SSPL config's are updated

- cli/src/factory_ops/unboxing/init
> EOS-15360-improvements: Ensure all services are started after unmaintenance command

- cli/src/factory_ops/unboxing/init
Signed-off-by: Anjali Somwanshi anjali.somwanshi@seagate.com
> EOS-16027: Unboxing Restart all services once CSM and SSPL config's are updated (commit set)

- srv/components/controller/files/scripts/controller-cli.sh
- srv/components/controller/files/scripts/provision.sh
- srv/components/controller/files/scripts/xml.sh
> EOS-15947: Use SFTP instead of FTP for doing the firmware update

- .gitignore
- api/python/provisioner/srv/salt/glusterfs/client/start.sls
- cli/src/replace_node/deploy-replacement
- srv/components/provisioner/config.sls
- srv/components/provisioner/files/glusterfshsaredstorage.service
- srv/components/provisioner/salt_master/files/salt-master.service
Signed-off-by: sradhanandpati sradhanand.pati@seagate.com
> EOS-15325 (sms20): Updating glusterfs service relation with salt-master

- pillar/components/firewall.sls
- srv/components/system/firewall/config.sls
> [EOS-16278] firewall configuration on the basis of pillar data

- srv/components/controller/files/scripts/provision.sh
- srv/components/controller/files/scripts/xml.sh
Handled following error cases:
1. controller goes down in middle of the fw update.
2. sftp command exits with non zero return code.
> EOS-16704: FW update over sftp- handle error cases.

- srv/components/controller/files/scripts/controller-cli.sh
- srv/components/controller/files/scripts/provision.sh
- srv/components/controller/files/scripts/xml.sh
The patch has following fixes:
EOS-16704: FW update: SFTP session returns with non-zero exit code (#841)
EOS-16704: FW update over sftp: handle error cases. (#839)
> SMS2: fw update fixes

- srv/components/system/firewall/sanity_check.sls
> EOS-16278: [BugFix]: Switch Firewall Settings on the fly

- srv/components/provisioner/salt_minion/files/minion
> EOS-15505: changes for configuring salt multi-master with failover

- files/scripts/profiling/README.md
- files/scripts/profiling/deployment_time_profiling.py
Script to generate the time profiling report by parsing the log files generated during deployment.
> EOS-16276: Deployment time profiling scripts

- srv/components/csm/prepare.sls
- srv/components/ha/iostack-ha/prepare.sls
- srv/components/hare/prepare.sls
> [EOS-16561],[EOS-16562],[EOS-16563]:Removes build-ha-args.yaml, cluster.yaml and build-ha-csm-args.yaml file

- api/python/provisioner/commands/deploy.py
- api/python/provisioner/commands/deploy_dual.py
- api/python/provisioner/commands/deploy_vm.py
- srv/components/misc_pkgs/openldap/init.sls
- srv/components/misc_pkgs/openldap/install.sls
- srv/components/s3server/config.sls
> [EOS-16639]:Remove OpenLDAP config from Provisioner

- api/python/provisioner/api.py
- api/python/provisioner/commands/__init__.py
- api/python/provisioner/commands/auto_deploy.py
- api/python/provisioner/commands/auto_deploy_vm.py
- api/python/provisioner/commands/check.py
- api/python/provisioner/commands/configure_setup.py
- api/python/provisioner/commands/deploy.py
- api/python/provisioner/commands/deploy_vm.py
- api/python/provisioner/commands/get_setup_info.py
- api/python/provisioner/commands/setup_provisioner.py
- api/python/provisioner/config.py
- api/python/provisioner/errors.py
- api/python/provisioner/inputs.py
- api/python/provisioner/salt_api/ssh.py
- cli/src/code_coverage/prvsnr-coverage.py
- files/scripts/profiling/deployment_time_profiling.py
- srv/components/misc_pkgs/openldap/init.sls
- srv/components/misc_pkgs/openldap/install.sls
- srv/components/misc_pkgs/openldap/prepare.sls
- srv/components/provisioner/files/cluster_sls.template
- test/conftest.py
- test/srv/modules/test_setup_conf.py
-------------------------------------------------------
1. OpenLDAP changes corrected
2. Call for pillar_export added as part of auto_deploy and auto_deploy_vm
3. pep8 fixes
4. API code corrections where necessary to align with new with mini-provisioner
> Code changes to improve mini-provisioner.

- api/python/provisioner/commands/pillar_export.py
> EOS-16560: cli-arg override to pillar_export api

- srv/components/motr/backup.sls
- srv/components/motr/update.sls
Placeholders for mini-provisioner calls were added
> [EOS-16910] - Add placeholders for mini-provisioner calls in scope of update

- cli/src/csm_admin_user.py
- srv/_modules/setup_conf.py
> EOS-17120: Minor fix in setup.yaml read logic

- api/python/provisioner/commands/pillar_export.py
> EOS-17148: remove list type to convert to json

- srv/components/csm/rollback.sls
- srv/components/ha/cortx-ha/restore.sls
- srv/components/ha/cortx-ha/rollback.sls
- srv/components/hare/restore.sls
- srv/components/hare/rollback.sls
- srv/components/s3server/restore.sls
- srv/components/s3server/rollback.sls
- srv/components/sspl/rollback.sls
- srv/components/uds/restore.sls
- srv/components/uds/rollback.sls
Add placeholders for mini-provisioner calls in scope of rollback	
- s3server
- hare
- cortx-ha
- sspl
- uds
- csm
> EOS-17021: Add placeholders for mini-provisioner calls in scope of rollback

- docs/Architecture/Southbound-Interface.md
- Corrected interfaces as per Mini-Provisioner Specifications
-----
[View rendered docs/Architecture/Southbound-Interface.md](https://github.com/Seagate/cortx-prvsnr/blob/mini-prov/docs/Architecture/Southbound-Interface.md)
> Mini-Provisioner Specifications

- api/python/provisioner/srv/salt/cortx_repos/files/etc/yum.repos.d/saltstack.repo
- api/python/setup.py
> EOS-16414: Update salt version to 3002.2

- api/python/provisioner/commands/setup_provisioner.py
- api/python/setup.py
- cli/src/common_utils/functions.sh
- cli/src/cortx-prereqs.sh
- devops/rpms/api/build_python_api.sh
- devops/rpms/cortx-prvsnr.spec
- files/etc/yum.repos.d/saltstack.repo
- srv/components/defaults.yaml
- srv/components/system/network/data/direct/init.sls
- srv/components/system/network/data/teamd/init.sls
- srv/components/system/network/mgmt/teamed/init.sls
- test/devops/rpms/test_buildrpm_sh.py
> NIC teaming for network interfaces

- srv/components/csm/backup.sls
- srv/components/csm/install.sls
- srv/components/csm/update.sls
- srv/components/ha/cortx-ha/backup.sls
- srv/components/ha/cortx-ha/update.sls
- srv/components/hare/update.sls
- srv/components/s3server/backup.sls
- srv/components/s3server/config.sls
- srv/components/s3server/update.sls
- srv/components/sspl/config.sls
- srv/components/sspl/update.sls
- srv/components/uds/backup.sls
- srv/components/uds/update.sls
Add placeholders for mini-provisioner calls in scope of update for
- s3server
- hare
- cortx-ha
> EOS-17022: Add placeholders for mini-provisioner calls in scope of update

- pillar/components/commons.sls
- srv/components/ha/haproxy/files/haproxy.cfg
- srv/components/provisioner/files/setup.yaml
- srv/components/s3server/config.sls
- srv/components/s3server/install.sls
- srv/components/s3server/prepare.sls
- srv/components/s3server/sanity_check.sls
> Improved S3 config calls for mini-provisioner

- srv/components/system/config/pillar_encrypt.sls
- srv/components/system/files/cortx_py_utils_requirements.txt
- srv/components/system/teardown.sls
> Install dependencies for cortx-py-utils

- pillar/components/commons.sls
> Consul version update

- api/python/setup.py
- cli/src/cortx_prep.sh
> Better Salt package management for version 3002.2+

- srv/components/system/config/hosts.sls
> EOS-17333: Update /etc/hosts with all NW interface IPs

- srv/components/provisioner/salt_minion/files/minion
Reverts Seagate/cortx-prvsnr#846
> Revert "EOS-15505: changes for configuring salt multi-master with failover"

- srv/components/csm/teardown.sls
- srv/components/ha/haproxy/teardown.sls
- srv/components/misc_pkgs/elasticsearch/stop.sls
- srv/components/misc_pkgs/elasticsearch/teardown.sls
- srv/components/misc_pkgs/kafka/teardown.sls
- srv/components/misc_pkgs/kibana/teardown.sls
- srv/components/misc_pkgs/nodejs/teardown.sls
- srv/components/misc_pkgs/rabbitmq/teardown.sls
- srv/components/misc_pkgs/rsyslog/teardown.sls
- srv/components/nfs/stop.sls
- srv/components/nfs/teardown.sls
- srv/components/s3server/teardown.sls
- srv/components/system/logrotate/teardown.sls
- srv/components/system/storage/multipath/config.sls
- srv/components/system/storage/multipath/stop.sls
- srv/components/system/storage/multipath/teardown.sls
- srv/components/system/teardown.sls
- srv/components/uds/teardown.sls
> EOS-16870: repair teardown states

- srv/components/s3clients/config.sls
- srv/components/system/config/hosts.sls
> Changes for S3Clients

- srv/components/s3server/install.sls
- srv/components/s3server/teardown.sls
> EOS-17486:Remove s3iamcli installation from s3server.install

- api/python/provisioner/commands/deploy_dual.py
- api/python/provisioner/commands/deploy_vm.py
- srv/components/ha/cortx-ha/config.sls
- srv/components/ha/cortx-ha/init.sls
- srv/components/ha/cortx-ha/sanity_test.sls
Signed-off-by: mazinamdar mazhar.inamdar@seagate.com
-------------------------------------------------------------------------------------------------------------
| Action | Node to execute on |
|--------|-----------------------|
| post_install | All nodes |
| config | Primary or active node in cluster |
| init | All nodes |
| cleanup | Primary or active node in cluster |
| reset | All nodes |
| test | Primary or active node in cluster |
> [EOS-17444] Setup HA on single node vm

- srv/components/s3server/config.sls
- srv/components/s3server/install.sls
> Ordering s3server config stages

- api/python/provisioner/api.py
- api/python/provisioner/commands/__init__.py
> EOS-17416: Use pillar to track the scope of rollback better

- pillar/components/openldap.sls
> EOS-17575: s3 iam user key change

- cli/buildrpm.sh
- devops/rpms/buildrpm.sh
> Update default value for version param

- docs/mocks.md
- srv/components/misc_pkgs/mocks/cortx/files/scripts/buildbundle.sh
- srv/components/misc_pkgs/mocks/cortx/install.sls
- a simple hotfix for bad jinja
- improvement for mocks docs
-----
[View rendered docs/mocks.md](https://github.com/andkononykhin2/cortx-prvsnr/blob/EOS-17598-hotfix-and-docs-update/docs/mocks.md)
> [EOS-17598] hotfix and docs update

- api/python/provisioner/api.py
- api/python/provisioner/commands/__init__.py
- api/python/provisioner/commands/sw_rollback.py
- api/python/provisioner/commands/sw_upgrade.py
- api/python/provisioner/salt.py
- pillar/components/upgrade.sls
> EOS-17542: Rollback API refinement

- srv/components/csm/teardown.sls
> EOS-17593: cortx-cli teardown order change

- files/scripts/monitoring/README.md
- files/scripts/monitoring/node_exporter_setup.sh
- files/scripts/monitoring/prom_monitor_setup.sh
-----
[View rendered files/scripts/monitoring/README.md](https://github.com/rahuljyoti65/cortx-prvsnr/blob/EOS-16275/files/scripts/monitoring/README.md)
> EOS-16275: Scripts and docs to setup monitoring service

- srv/components/controller/files/scripts/provision.sh
> EOS-16885: Firmware update fails if ssh key is not added to the list of known hosts

- srv/components/provisioner/files/cluster_sls.template
- srv/components/system/config/hosts.sls
> EOS-18402: Pillar Config to include FQDN for server node specific info

- docs/saltstack.md
- srv/components/provisioner/config/machine_id/init.sls
- srv/components/provisioner/config/machine_id/refresh_grains.sls
- srv/components/provisioner/config/machine_id/refresh_machine_id.sls
- srv/components/provisioner/config/refresh_machine_id.sls
1. delete old machine-id
2. create new machine-id
3. sync grains data
> [EOS-18351] Refresh machine id of the system

- srv/components/system/config/hosts.sls
> Fix for RabbitMQ server config after FQDN changes

- api/python/provisioner/commands/setup_provisioner.py
- srv/components/hare/config.sls
> Fix in setup_provisioner.py for provisioner config

- api/python/provisioner/commands/setup_provisioner.py
- srv/components/provisioner/salt_master/files/master
- srv/components/provisioner/salt_minion/files/minion
> Fix the cluster.sls generation logic

- docs/testing.md
- test/r2.txt
I prepared doc with instruction how to deploy docker and configure testing environment. Also I updated the test scenario for EOS-18337
-----
[View rendered docs/testing.md](https://github.com/Seagate/cortx-prvsnr/blob/EOS-18337-docs/docs/testing.md)
> EOS-18337: Docs: Update testing documentation and docker deployment guide

- api/python/provisioner/cli_parser.py
- api/python/provisioner/commands/auto_deploy.py
- api/python/provisioner/commands/auto_deploy_vm.py
- api/python/provisioner/commands/generate_roster.py
Tried to improve description from help for API.
> Improve help section of python API

- srv/components/system/config/init.sls
- srv/components/system/config/tmp_conf.sls
> EOS-18430:SMS2: Exclude auto cleanup of specific files/directories in /tmp

- pillar/node_info/node_data.sls
- srv/components/provisioner/files/cluster_sls.template
Add unique machine_id from all nodes in cluster.sls
> [EOS-18451] Update machine_ids of all nodes in cluster.sls

- cli/src/factory_ops/unboxing/init
- cli/src/factory_ops/unboxing/network/public_data
- cli/src/factory_ops/unboxing/network/public_mgmt
- srv/components/controller/files/scripts/provision.sh
------------------------------------------------------------------------------------------------------
Fixes:
- EOS-16885: Firmware update fails if ssh key is not added to the list of known hosts
- EOS-16798: beta6: Weka: "LDR R1" Unit 6, build#531: 6019P: publicDataInterface networkScript shows GATEWAY set to NETMASK octet
- EOS-17036: "No Route to host" error observed during s3 operations intermittently
- EOS-17562: Reconfigure firewall after network update
> SMS2: FW Update, unboxing network and firewall fixes

- srv/components/provisioner/files/cluster_sls.template
> Server nodes should be dict not an array of dict

- devops/ci/multi_node_deploy/Jenkinsfile
- devops/ci/multi_node_deploy/Jenkinsfile_3Node_Deploy
> EOS-17820: 3-node VM deployment implementation and integration - Phase-1

- devops/ci/multi_node_deploy/Jenkinsfile_3Node_Deploy
- devops/ci/multi_node_deploy/Jenkinsfile_3Node_Destroy
> 3Node Destroy Jenkinsfile and Seagate Licence Added

- api/python/provisioner/ssh.py
- cli/src/cortx_prep.sh
> EOS-18466: support for root password through sshpass env variable

- api/python/provisioner/__metadata__.py
> Update Provisioner API version to 2.0.42

- srv/components/system/network/data/direct/init.sls
- srv/components/system/network/data/public/init.sls
- srv/components/system/network/mgmt/public/init.sls
- srv/components/system/network/mgmt/service_port/init.sls
> Improvements for network states

- api/python/provisioner/ssh.py
> Quickfix for environ exception for SSHPASS-Newer

- cli/src/factory_ops/unboxing/network/public_mgmt
> EOS-18509: UnBoxing Script is failing when static IP network configuration option is selected

- srv/components/sspl/config/commons.sls
> Fix common_configs for SSPL in Consul

- api/python/provisioner/commands/__init__.py
> [EOS-18499] Fix create user provisioner API

- devops/ci/multi_node_deploy/Jenkinsfile_3Node_Deploy
- devops/ci/single_node_deploy/Jenkinsfile_Deploy
- devops/ci/single_node_deploy/Jenkinsfile_Deploy_ISO
- devops/ci/single_node_deploy/Jenkinsfile_Destroy
> Jenkinsfile archive improvements

- srv/components/misc_pkgs/rabbitmq/config/base.sls
> Fix issue with rabbitmq failure during Jenkins

- pillar/components/firewall.sls
- srv/components/system/firewall/sanity_check.sls
> EOS-17829: Validation for Open Ports in Firewall

- api/python/provisioner/api_spec.yaml
- api/python/provisioner/commands/destroy.py
- api/python/provisioner/config.py
- srv/components/provisioner/teardown/package_remove.sls
- srv/components/sspl/teardown.sls
- srv/components/system/teardown.sls
Initial API to destroy single node cortx on vm and HW using salt ssh.
> [EOS-18498] Common API to destroy cortx on vm and HW

- cli/src/virtual_appliance/bootstrap.sh
> fix for sspl issue in bootstrap script

- api/python/README.md
-----
[View rendered api/python/README.md](https://github.com/Seagate/cortx-prvsnr/blob/codacy-fixes/api/python/README.md)
> Codacy fixes in Readme.md file

- api/python/provisioner/commands/_basic.py
- api/python/provisioner/commands/resource.py
Signed-off-by: Andrey Kononykhin <andkononykhin@gmail.com>
> Main->Stable Candidate-09032021

- images/docker/setup_systemd.sh
Add installation of `initscripts` package to docker container.
> [Docker] Add installation of initv scripts to docker container

- srv/_modules/sspl.py
- srv/components/sspl/health_view/config/generate.sls
- srv/components/sspl/health_view/config/merge.sls
> Improvements to HealthMap Schema

- test/r2.txt
I updated the `r2.txt` testing doc by improving EOS-18337 testing procedure
> [Test][Doc]: Fix r2.txt testing doc for EOS-18337

- test/README.md
- test/api/python/integration/test_api.py
- test/api/python/integration/test_hare.py
- test/api/python/integration/test_pillar_targets.py
- test/api/python/integration/test_rollback.py
- test/api/python/integration/test_setup.py
- test/api/python/provisioner/test_cli_parser.py
- test/api/python/provisioner/test_commands.py
- test/api/python/provisioner/test_pillar.py
- test/build_helpers/build_bundles/test_build_bundles.py
- test/bvt/test_bvt.py
- test/cli/src/test_configure.py
- test/cli/src/test_functions.py
- test/cli/src/test_setup_provisioner.py
- test/cli/src/test_start.py
- test/cli/src/test_stop.py
- test/devops/rpms/test_buildrpm_sh.py
- test/pillar/roles/test_primary_sls.py
- test/pillar/test_top_sls.py
- test/srv/components/csm/test_csm_config_sls.py
- test/srv/components/misc_pkgs/swupdate/test_repo.py
- test/srv/components/provisioner/test_provisioner.py
- test/srv/modules/test_setup_conf.py
-----
[View rendered test/README.md](https://github.com/rahuljyoti65/cortx-prvsnr/blob/coverage-issue-fix/test/README.md)
> EOS-18738: Temporary fix for coverage issue

- srv/components/system/firewall/config.sls
> EOS-18766-sms: Disable port 443 in firewall on Mgmt NW interface

- pillar/components/firewall.sls
- srv/components/system/firewall/config.sls
- srv/components/system/firewall/init.sls
- srv/components/system/firewall/install.sls
- srv/components/system/firewall/sanity_check.sls
- srv/components/system/firewall/teardown.sls
> Update management zone and use public zone as default

- api/python/provisioner/commands/deploy.py
- api/python/provisioner/commands/deploy_vm.py
- pillar/components/firewall.sls
> EOS-18766: Disable port 443 in firewall on Mgmt NW interface.

- pillar/node_info/node_data.sls
- srv/components/provisioner/files/cluster_sls.template
Problem : Node Id is not set in cluster.sls
Solution: Added node ID in cluster.sls using mine data .
> [EOS-18578] Add node_id in cluster.sls

- docs/User-Guides/LDR-R1 HW Deployment.md
- docs/User-Guides/LDR-R1 VM Deployment.md
- srv/components/provisioner/config.sls
- srv/components/system/config/hosts.sls
> EOS-17315: OVA fix for hosts file and setting salt-master default configuration in case of single node

- api/python/provisioner/commands/deploy_vm.py
- devops/ci/multi_node_deploy/Jenkinsfile_3Node_Deploy
- srv/components/misc_pkgs/openldap/install.sls
- srv/components/misc_pkgs/openldap/start.sls
> EOS-18270: 3-node VM deployment implementation and integration - Phase-2 - 3rd Party SW

- docs/testing.md
- test/build_helpers/build_bundles/test_build_bundles.py
- test/build_helpers/build_prvsnr_pkgs/conftest.py
-----
[View rendered docs/testing.md](https://github.com/andkononykhin2/cortx-prvsnr/blob/fixes-test-helper-execution/docs/testing.md)
> [testing] un-skips test and resolves argparse conflict

- api/python/setup.py
- cli/src/code_coverage/prvsnr-coverage.py
- test/api/python/integration/test_api.py
- test/api/python/integration/test_hare.py
- test/api/python/integration/test_pillar_targets.py
- test/api/python/integration/test_rollback.py
- test/api/python/integration/test_setup.py
- test/bvt/test_bvt.py
- test/cli/src/test_configure.py
- test/cli/src/test_functions.py
- test/cli/src/test_setup_provisioner.py
- test/cli/src/test_start.py
- test/cli/src/test_stop.py
- test/devops/rpms/test_buildrpm_sh.py
- test/pillar/roles/test_primary_sls.py
- test/pillar/test_top_sls.py
- test/srv/components/csm/test_csm_config_sls.py
- test/srv/components/misc_pkgs/swupdate/test_repo.py
- test/srv/components/provisioner/test_provisioner.py
- test/srv/modules/test_setup_conf.py
> EOS-18738: Unskip non-unit test cases

- api/python/provisioner/inputs.py
one more failure case was identified
> fixes base logic of cli args parsing

- pillar/samples/config.ini
- pillar/samples/config_vm.ini
- pillar/samples/dualnode.cluster.sls
- pillar/samples/generic_config.ini
- pillar/samples/jbod_config.ini
- pillar/samples/singlenode.cluster.sls
1. Change role of secondary nodes to openldap_servers for first 3 nodes
2. Change openldap_master to openldap_server
> EOS-18576: Address issues in 3 node VM deployment.

- api/python/provisioner/commands/auto_deploy.py
- api/python/provisioner/commands/auto_deploy_vm.py
> EOS-17115: missed to accomodate change in auto_deploy

- srv/components/controller/ntp.sls
> EOS-18826: Fix rendering of components.controller.ntp state.

- cli/src/virtual_appliance/bootstrap.sh
> EOS-18857: OVA: S3-configuration missing after cluster bootstrap

- srv/components/provisioner/files/cluster_sls.template
- srv/components/system/files/confstore_template.j2
> Adding storage enclosure keys to confstore

- srv/components/system/files/confstore_template.j2
> Fix for durability keys in confstore

- api/python/provisioner/commands/set_swupgrade_repo.py
- api/python/provisioner/inputs.py
- test/r2.md
- test/r2.txt
I updated the `r2.txt` testing docs and made small fixes for `set_swupgrade_repo` command
> EOS-15746: Test docs update & code fix

- srv/_grains/platform.py
> EOS-18917: Custom grains for lr-serial-number

- api/python/provisioner/commands/setup_provisioner.py
> EOS-19090:ConfStore keys does not contain enclosure_id for storage_enclosure parameters.

- api/python/provisioner/commands/configure_setup.py
- api/python/provisioner/commands/validator/__init__.py
- api/python/provisioner/commands/validator/enclosure.py
- api/python/provisioner/commands/validator/network.py
- api/python/provisioner/commands/validator/node.py
- api/python/provisioner/commands/validator/release.py
> EOS-18920: Patch-1: create separate validation modules and remove from configure_setup api

- test/r2.md
-----
[View rendered test/r2.md](https://github.com/Seagate/cortx-prvsnr/blob/r2-test-file-update/test/r2.md)
> Test File Update: added test scenarios for clusterID and ports adjustments

- api/python/provisioner/commands/configure_setup.py
- api/python/provisioner/commands/validator/__init__.py
- api/python/provisioner/commands/validator/config_sections.py
- api/python/provisioner/commands/validator/enclosure.py
- api/python/provisioner/commands/validator/network.py
- api/python/provisioner/commands/validator/node.py
- api/python/provisioner/commands/validator/release.py
Changes updated over the same branch for PR #1060 , will rebase once that is merged.
> EOS-18920: Patch-2: Config validations added

- srv/components/misc_pkgs/nodejs/init.sls
- srv/components/misc_pkgs/statsd/init.sls
> EOS-19127: Add checkpoint flags for statsd and nodejs

- srv/_modules/controller_cli.py
- srv/components/controller/files/scripts/controller-cli.sh
- srv/components/system/storage/enclosure_id/config/set.sls
> EOS-18903: write module for fetching enclosure id.

- srv/components/system/files/confstore_template.j2
> EOS-19131:[ConfStore] ConfStore should provide pool type information and allowed_failures

- api/python/provisioner/__metadata__.py
- devops/rpms/api/build_python_api.sh
Signed-off-by: Andrey Kononykhin <andrey.kononykhin@seagate.com>
> removes explicit dependency link for api rpm

- api/python/MANIFEST.in
- api/python/provisioner/ui/__init__.py
Added  cli_spec.yaml and attrs_spec.yaml files in MANIFEST.in
Added init file so that provisioner/ui dir can be consider to add in python package
> [HOTFIX] Added some missing file in python package cortx-prvsnr 

- EOS-19173.patch
- api/python/provisioner/commands/__init__.py
-----
[View rendered README.md](https://github.com/Seagate/cortx-prvsnr/blob/EOS-19173/README.md)
> [EOS-19173] build 607 - Update - Release Version is Still shown as 1.0

- api/python/provisioner/commands/bootstrap/node.py
- api/python/provisioner/commands/configure_node.py
- api/python/provisioner/commands/configure_setup.py
- api/python/provisioner/commands/confstore_export.py
- api/python/provisioner/commands/validator/config_sections.py
- api/python/provisioner/config.py
- api/python/provisioner/resources/consul.py
- api/python/provisioner/ui/README.md
- api/python/provisioner/ui/question_window.py
- srv/_grains/network.py
- srv/_grains/platform.py
- srv/_modules/controller_cli.py
- test/r2.md
-----
[View rendered api/python/provisioner/ui/README.md](https://github.com/Seagate/cortx-prvsnr/blob/codacy-fixes/api/python/provisioner/ui/README.md)
[View rendered test/r2.md](https://github.com/Seagate/cortx-prvsnr/blob/codacy-fixes/test/r2.md)
> Codacy fixes for 'main' PR 1081

- api/python/provisioner/commands/__init__.py
> EOS-19173-update-607- Release Version is Still shown as 1.0

- api/python/provisioner/config.py
- api/python/provisioner/resources/consul.py
- api/python/provisioner/scm/saltstack/rc_sls/base.py
- api/python/provisioner/scm/saltstack/rc_sls/consul.py
> Codacy fixes.

- srv/components/ha/haproxy/files/haproxy.cfg
> Fix for HAProxy default binds.

- srv/components/system/files/confstore_template.j2
> ConfStore key fixes

- srv/components/defaults.yaml
> Change typo in defaults.yaml

- api/python/provisioner/commands/setup_provisioner.py
- pillar/node_info/node_data.sls
- srv/components/provisioner/files/storage_sls.template
- srv/components/system/config/sync_salt.sls
- srv/components/system/files/confstore_template.j2
- srv/components/system/storage/enclosure_id/config/set.sls
- srv/components/system/storage/enclosure_id/config/sync.sls
> Move enclosure-id to mine data

- cli/src/virtual_appliance/bootstrap.sh
- docs/User-Guides/LDR-R1 VM Deployment.md
- srv/components/system/firewall/config.sls
- srv/components/system/firewall/teardown.sls
-----
[View rendered docs/User-Guides/LDR-R1 VM Deployment.md](https://github.com/Seagate/cortx-prvsnr/blob/EOS-18817-sms2/docs/User-Guides/LDR-R1 VM Deployment.md)
> EOS-18817-sms2: Fix Firewall Issues for 28100 port

- cli/src/virtual_appliance/bootstrap.sh
- docs/User-Guides/LDR-R1 VM Deployment.md
- srv/components/provisioner/config.sls
- srv/components/system/firewall/config.sls
- srv/components/system/firewall/init.sls
- srv/components/system/firewall/teardown.sls
> EOS-19398: Bootstrap script failing due to salt-master not starting up

- test/r2.md
Signed-off-by: nayakkishan <kishan.nayak@seagate.com>
-----
[View rendered test/r2.md](https://github.com/nayakkishan/cortx-prvsnr/blob/testfileupdate/test/r2.md)
> Updating ticket status in r2.md file

- devops/ci/multi_node_deploy/3node_deploy.jenkinsfile
- devops/ci/single_node_deploy/deploy.jenkinsfile
- devops/ci/single_node_deploy/deploy_iso.jenkinsfile
- pillar/samples/config.ini
- pillar/samples/config_vm.ini
- srv/components/provisioner/files/cluster_sls.template
- srv/components/system/files/confstore_template.j2
> EOS-19434:Add default values for durability keys

- srv/components/misc_pkgs/kafka/config.sls
> Use zookeeper client port in Kafka server.properties.

- srv/components/s3server/config/prepare.sls
- test/r2.md
> [EOS-19396]-Ensure dependent services are started for S3Server

- cli/src/cortx_prep.sh
- devops/ci/multi_node_deploy/3node_deploy.jenkinsfile
- devops/ci/multi_node_deploy/3node_destroy.jenkinsfile
- devops/ci/single_node_deploy/deploy.jenkinsfile
- devops/ci/single_node_deploy/destroy.jenkinsfile
- srv/components/system/config/hosts.sls
> Add Debug to deployment jobs in Jenkins

- images/os/build
- images/os/centos_78_2003_hyperv.json
- images/os/centos_78_2003_vmware.json
- images/os/kickstart_centos_75_1804.cfg
- images/os/kickstart_centos_78_2003.cfg
> packer files for centos-7.8

- srv/components/csm/init.sls
- srv/components/ha/cortx-ha/init.sls
- srv/components/hare/init.sls
- srv/components/motr/init.sls
- srv/components/s3server/init.sls
> EOS-19559: removing default test interface calls from components

- api/python/provisioner/runner.py
> [EOS-19561] Added nowait paramter for provisioner CLI

- api/python/provisioner/__init__.py
- api/python/provisioner/_api_cli.py
- api/python/provisioner/api.py
- api/python/provisioner/api_spec.yaml
- api/python/provisioner/inputs.py
- api/python/provisioner/params_spec.yaml
- test/r2.md
> EOS-19231: North Bound Command API Implementation - Data Network

- api/python/provisioner/inputs.py
> fix-data-network-api: Fix api data netwrok issue

- srv/components/misc_pkgs/kafka/config.sls
> HOTFIX: fix typo in Kafka config generation code

- srv/components/misc_pkgs/kafka/config.sls
> HOTFIX: fix typo in Kafka config generation code (#1138)

- test/r2.md
-----
[View rendered test/r2.md](https://github.com/nayakkishan/cortx-prvsnr/blob/testfile_update_sprint41/test/r2.md)
> Text-execution status update for sprint-41

- srv/components/ha/corosync-pacemaker/config/authorize.sls
- srv/components/ha/corosync-pacemaker/config/base.sls
> HA hotfix: Provide correct pillar names for password decryption

- pillar/components/sspl.sls
> Changed polling_interval for raidintegrity sensor in sspl.sls.

- api/python/provisioner/commands/__init__.py
- api/python/provisioner/commands/confstore_export.py
- api/python/provisioner/commands/set_swupdate_repo.py
- api/python/provisioner/commands/set_swupgrade_repo.py
- api/python/provisioner/config.py
- api/python/provisioner/errors.py
- api/python/provisioner/inputs.py
- api/python/provisioner/lock.py
- api/python/provisioner/srv/salt/repos/upgrade.sls
- api/python/provisioner/utils.py
- api/python/setup.py
- srv/_modules/pillar_ops.py
- srv/components/ha/corosync-pacemaker/config/authorize.sls
- srv/components/ha/corosync-pacemaker/config/base.sls
- test/api/python/integration/setup/conftest.py
- test/conftest.py
- test/debug/test_debug.py
- test/r2.md
- test/testapi/__init__.py
- test/testapi/defs.py
- test/testapi/helper.py
- test/testapi/integration.py
- test/testapi/test_examples.py
-----
[View rendered test/r2.md](https://github.com/Seagate/cortx-prvsnr/blob/main-candidate-20-Apil-21-III/test/r2.md)
> Main candidate 20 April 21 III

- api/python/provisioner/utils.py
> Remove tricky characters from set of special characters

- api/python/provisioner/commands/__init__.py
> EOS-19668: creating csm users folder, if not present

- api/python/provisioner/commands/__init__.py
- srv/components/system/config/service_user.sls
> EOS-19668: HOTFIX: change secret to password

- devops/ci/single_node_deploy/deploy.jenkinsfile
> fix storage config check in single node jenkins job

- cli/src/cortx_prep.sh
> Cortx_prep_fix for hw deployment

- srv/components/ha/cortx-ha/config/config.sls
> EOS-19751: Run cortx-ha.config on all nodes.

- devops/ci/single_node_deploy/deploy.jenkinsfile
> Generate storage device list dynamically

- cli/src/virtual_appliance/bootstrap.sh
- docs/User-Guides/Deploy VM Hosted Repo.md
- docs/User-Guides/Deploy VM ISO Repo.md
-----
[View rendered docs/User-Guides/VM-Deployment.md](https://github.com/rahuljyoti65/cortx-prvsnr/blob/EOS-18817/docs/User-Guides/VM-Deployment.md)
> EOS-18817, EOS-19760: Fix Firewall Issues for 28100 port

- api/python/provisioner/commands/destroy.py
- api/python/provisioner/srv/salt/provisioner/files/post_setup.sh
- cli/src/cortx_prep.sh
- cli/src/virtual_appliance/bootstrap.sh
- devops/ci/multi_node_deploy/3node_deploy.jenkinsfile
- devops/ci/multi_node_deploy/3node_destroy.jenkinsfile
- devops/ci/single_node_deploy/deploy.jenkinsfile
- devops/ci/single_node_deploy/deploy_iso.jenkinsfile
- devops/ci/single_node_deploy/destroy.jenkinsfile
- docs/Architecture/Architectural-Overview.md
- docs/User-Guides/Deploy VM Hosted Repo.md
- docs/User-Guides/Deploy VM ISO Repo.md
- images/os/centos_78_2003_hyperv.json
- srv/components/ha/cortx-ha/config/config.sls
- srv/components/provisioner/teardown/package_remove.sls
- srv/components/system/firewall/teardown.sls
- srv/components/system/storage/glusterfs/teardown/cache_remove.sls
- srv/components/system/storage/glusterfs/teardown/package_remove.sls
- test/r2.md
-----
[View rendered docs/Architecture/Architectural-Overview.md](https://github.com/Seagate/cortx-prvsnr/blob/main-candidate-260421/docs/Architecture/Architectural-Overview.md)
[View rendered docs/User-Guides/Deploy VM Hosted Repo.md](https://github.com/Seagate/cortx-prvsnr/blob/main-candidate-260421/docs/User-Guides/Deploy VM Hosted Repo.md)
[View rendered docs/User-Guides/Deploy VM ISO Repo.md](https://github.com/Seagate/cortx-prvsnr/blob/main-candidate-260421/docs/User-Guides/Deploy VM ISO Repo.md)
[View rendered test/r2.md](https://github.com/Seagate/cortx-prvsnr/blob/main-candidate-260421/test/r2.md)
> Main candidate 260421

- test/r2.md
Updated R2.md table
-----
[View rendered test/r2.md](https://github.com/Seagate/cortx-prvsnr/blob/r2update/test/r2.md)
> update R2.md tests

- api/python/provisioner/commands/setup_provisioner.py
> EOS-19773: adding pillar_encrypt as part of bootstrap

- api/python/provisioner/commands/setup_provisioner.py
- srv/components/hare/config/init.sls
- test/r2.md
-----
[View rendered test/r2.md](https://github.com/Seagate/cortx-prvsnr/blob/main-candidate-270421/test/r2.md)
> Main candidate 270421

- srv/components/misc_pkgs/elasticsearch/sanity_check.sls
> Wait for elasticsearch to start.

- srv/components/misc_pkgs/kafka/config.sls
- srv/components/misc_pkgs/kafka/files/zookeeper.properties
- srv/components/misc_pkgs/kafka/install.sls
- srv/components/misc_pkgs/kafka/start.sls
- srv/components/misc_pkgs/kafka/stop.sls
- srv/components/misc_pkgs/kafka/teardown.sls
> EOS-19568:Use kafka rpm to install and service files to manage kafka

- api/python/provisioner/commands/destroy.py
- cli/src/destroy-vm
- devops/ci/single_node_deploy/destroy.jenkinsfile
> Fixing teardown of kafka and cortx-utils

- devops/ci/multi_node_deploy/3node_destroy.jenkinsfile
- devops/ci/single_node_deploy/destroy.jenkinsfile
Single node destroy updated : included destroy stages
> Jenkins :Single node destroy fix

- cli/src/virtual_appliance/bootstrap.sh
- srv/components/misc_pkgs/kafka/teardown.sls
> EOS-19760:Bootstrap script is failing for R2 OVA

- api/python/provisioner/commands/deploy_vm.py
Removed mounting of metadata device before iopath states
> [Fix] Removed mounting of metadata deivce to /var/motr

- cli/src/code_coverage/prvsnr-coverage.py
> EOS-19757: add command to upload the coverage report generated in coverage script

- api/python/provisioner/inputs.py
- api/python/provisioner/params_spec.yaml
> EOS-19798: updates in mismatch param names

- api/python/provisioner/commands/deploy.py
- api/python/provisioner/commands/deploy_vm.py
- api/python/provisioner/commands/destroy.py
- api/python/provisioner/srv/salt/ssh/check.sls
- api/python/provisioner/srv/salt/ssh/files/config
- api/python/provisioner/utils.py
This reverts commit 3b1c144aa225beb222e1ecf2110f106741889da1.
> Revert "EOS-19834: Fix issues for Cortx-ha deployment for 3 node (#1199)"

- test/r2.md
-----
[View rendered test/r2.md](https://github.com/nayakkishan/cortx-prvsnr/blob/r2.md_update_Sprint-42/test/r2.md)
> Ticket status update in r2.md for sprint-42

- api/python/provisioner/inputs.py
- api/python/provisioner/params_spec.yaml
> [EOS-20284] added mtu for mgmt and data network

- srv/components/provisioner/salt_master/files/master
> EOS-19639-update salt-master timeout

- test/r2.md
-----
[View rendered test/r2.md](https://github.com/Seagate/cortx-prvsnr/blob/update-tests/test/r2.md)
> update tests in R2.md

- srv/components/misc_pkgs/kafka/config.sls
- srv/components/misc_pkgs/kafka/files/zookeeper.properties
- srv/components/misc_pkgs/kafka/sanity_check.sls
- srv/components/misc_pkgs/kafka/start.sls
- srv/components/misc_pkgs/kafka/stop.sls
> EOS-20463: Improvisations for Kafka service check

- srv/components/misc_pkgs/kafka/sanity_check.sls
- srv/components/misc_pkgs/kafka/start.sls
> Fixes for kafka sanity_check

- api/python/provisioner/srv/salt/ssh/config.sls
> [EOS-20486] Create copy of id_rsa_prvsnr as id_rsa 

- images/os/centos_78_2003_vmware.json
- images/os/centos_78_2003_vsphere.json
- images/os/kickstart_centos_78_2003.cfg
> Updates to packer to provision for release build ISO

- api/python/provisioner/srv/salt/ssh/config.sls
- cli/src/virtual_appliance/bootstrap.sh
- devops/ci/multi_node_deploy/3node_deploy.jenkinsfile
- devops/ci/multi_node_deploy/3node_destroy.jenkinsfile
- devops/ci/single_node_deploy/deploy.jenkinsfile
- devops/ci/single_node_deploy/deploy_iso.jenkinsfile
- devops/ci/single_node_deploy/destroy.jenkinsfile
- images/os/centos_78_2003_vmware.json
- images/os/centos_78_2003_vsphere.json
- images/os/kickstart_centos_78_2003.cfg
- srv/components/system/config/pillar_encrypt.sls
- srv/components/system/install.sls
> Main candidate 070521

- devops/ci/multi_node_deploy/3node_destroy.jenkinsfile
- devops/ci/single_node_deploy/destroy.jenkinsfile
> Fix storage issue by reclaiming storage.

- api/python/provisioner/commands/deploy.py
- api/python/provisioner/commands/deploy_vm.py
> EOS-20526: Run Cortx-HA component sequentially on nodes.

- api/python/provisioner/commands/deploy.py
- api/python/provisioner/commands/deploy_vm.py
> EOS-20526: Run Cortx-HA component sequentially on nodes. (#1238)

- api/python/provisioner/api_spec.yaml
- api/python/provisioner/commands/create_service_user.py
- api/python/provisioner/commands/deploy.py
- api/python/provisioner/commands/deploy_vm.py
- cli/src/virtual_appliance/bootstrap.sh
- devops/ci/multi_node_deploy/3node_destroy.jenkinsfile
- devops/ci/single_node_deploy/destroy.jenkinsfile
- srv/components/system/config/service_user.sls
Provisioner cli to create service user.
> [EOS-20439] Service user provisioner CLI

- srv/components/system/storage/config.sls
- srv/components/system/storage/teardown/init.sls
> EOS-20503: Disable 2GB swap on LR R1 SMS2

- docs/User-Guides/LDR-R1 HW Deployment.md
- docs/User-Guides/LDR-R1 Node Replacement.md
- srv/components/system/firewall/config.sls
Issues addressed:
- Open port 80 only on Management Interface
- Open port for GlusterFS on HW during unboxing
> EOS-20519: Update firewall config with fixes and documents for R1

- srv/components/system/storage/config/config.sls
> EOS-20503: Disable 2GB SWAP on LR nodes

- api/python/provisioner/commands/cluster_id.py
- api/python/provisioner/commands/setup_provisioner.py
- srv/components/provisioner/config/cluster_id/init.sls
- srv/components/provisioner/config/cluster_id/set.sls
> EOS-20506: cluster-id setup file in all nodes

- api/python/provisioner/commands/deploy.py
- api/python/provisioner/commands/deploy_dual.py
- api/python/provisioner/commands/deploy_vm.py
Retrieve node list from pillar and run cortx-ha sequentially on all secondary nodes.
> [cortx-ha-sequence] run cortx-ha sequentially on secondaries

- srv/components/provisioner/salt_master/files/master
- srv/components/provisioner/salt_minion/files/minion
> [EOS-20601]: 3 node deployment failed in 'ha' component using build #189

- test/r2.md
-----
[View rendered test/r2.md](https://github.com/nayakkishan/cortx-prvsnr/blob/update_r2.md/test/r2.md)
> Updating r2.md file for sprint-43

- lr-cli/cortx_setup/network.py
- lr-cli/cortx_setup/node.py
- lr-cli/setup.py
1. Add lr-cli directory
2. create cortx_setup package with initial config in setup.py
3. Add wrapper for `configure network` which can be invoked through `nodecli` 
> Address- EOS-20437: Configure Network and EOS-20438: Factory Node Initialize

- lr-cli/cortx_setup/signature.py
> EOS-19898: Codacy issues missed in PR #1247

- srv/components/misc_pkgs/kafka/start.sls
- srv/components/misc_pkgs/kafka/stop.sls
> [EOS-20716] fix service check command

- devops/ci/multi_node_deploy/3node_deploy.jenkinsfile
- devops/ci/multi_node_deploy/3node_destroy.jenkinsfile
- devops/ci/single_node_deploy/deploy.jenkinsfile
- devops/ci/single_node_deploy/deploy_iso.jenkinsfile
- devops/ci/single_node_deploy/destroy.jenkinsfile
- pillar/samples/config_vm.ini
- srv/components/misc_pkgs/openldap/init.sls
- srv/components/system/config/ssh_check.sls
> EOS-20563: Addition of Management VIP to Deploy jobs

- devops/ci/multi_node_deploy/3node_destroy.jenkinsfile
- devops/ci/single_node_deploy/destroy.jenkinsfile
> Stop cluster services during teardown to remove mgmt_vip from network-interface

- cli/src/virtual_appliance/bootstrap.sh
> EOS-20522: Bootstrap script require firewall fixes for OVA 1.0.4

- cli/src/virtual_appliance/bootstrap.sh
> EOS-20822: Bootstrap script require firewall fixes for OVA R2

- lr-cli/cortx_setup/config.py
Create parent dir in case of confstore.
> [EOS-20791] Create parent dir for consfstore file

- api/python/provisioner/api.py
- api/python/provisioner/commands/__init__.py
- api/python/provisioner/commands/set_swupdate_repo.py
- api/python/provisioner/commands/upgrade/get_swupgrade_info.py
- api/python/provisioner/commands/upgrade/set_swupgrade_repo.py
- images/docker/setup_system_packages.sh
- test/api/python/provisioner/test_sw_upgrade.py
I implemented API to query ISO content. I added test to cover this case
> EOS-19956: Implement API to query ISO contents

- api/python/provisioner/__metadata__.py
- api/python/provisioner/cli_spec.yaml
- api/python/provisioner/commands/validator/validator.py
- api/python/provisioner/config.py
- api/python/provisioner/resources/provisioner.py
- api/python/provisioner/resources/saltstack.py
- api/python/provisioner/scm/saltstack/rc_sls/base.py
- api/python/provisioner/scm/saltstack/rc_sls/provisioner.py
- api/python/provisioner/srv/salt/provisioner/files/post_setup.sh
- api/python/provisioner/srv/salt/resources/3rd_party/saltstack/fileroot.example
- api/python/provisioner/srv/salt/resources/cortx/provisioner/api/files/post_setup.sh
- api/python/provisioner/srv/salt/resources/cortx/provisioner/api/init.sls
- api/python/provisioner/srv/salt/resources/cortx/provisioner/api/install.sls
- api/python/provisioner/srv/salt/resources/cortx/provisioner/core/install/init.sls
- api/python/provisioner/srv/salt/resources/cortx/provisioner/core/install/local.sls
- api/python/provisioner/srv/salt/resources/cortx/provisioner/core/install/package.sls
- api/python/provisioner/srv/salt/resources/cortx/provisioner/fileroot.example
- api/python/provisioner/srv/salt/resources/cortx/provisioner/pillar.example
- api/python/provisioner/utils.py
- docs/Development/resources.md
That PR solves two things:
- provides new resource based implementation for provisioner resources installation on a set of nodes
- makes automation for sw upgrade testing infra preparation much easier
New resources are described in updated [resource.md](https://github.com/andkononykhin2/cortx-prvsnr/blob/EOS-19957_EOS-19964_provisioner-resources/docs/Development/resources.md) doc.
-----
[View rendered docs/Development/resources.md](https://github.com/andkononykhin2/cortx-prvsnr/blob/EOS-19957_EOS-19964_provisioner-resources/docs/Development/resources.md)
> [EOS-19957][EOS-19964] adds provisioner resources implementation

- lr-cli/cortx_setup/api_spec.yaml
- lr-cli/cortx_setup/commands/__init__.py
- lr-cli/cortx_setup/commands/node/prepare/firewall.py
- lr-cli/setup.py
> EOS-20662: Field Prepare Firewall Configuration

- srv/components/provisioner/teardown/remove_setup_files.sls
> EOS-20793: check presence of all /etc files before deleting

- api/python/provisioner/commands/upgrade/get_swupgrade_info.py
- api/python/provisioner/commands/upgrade/remove_swupgrade_repo.py
- api/python/provisioner/commands/upgrade/set_swupgrade_repo.py
I prepare the fix and improvements of the set of SW upgrade commands: I made them more failure tolerant
> [SW-Upgrade][Fix]: I prepare the fix and improvements of the set of SW upgrade commands: I made them more failure tolerant

- lr-cli/cortx_setup/api_spec.yaml
- lr-cli/cortx_setup/commands/__init__.py
- lr-cli/cortx_setup/commands/node/prepare/time.py
> EOS-20659: Field Prepare: Time configuration using cortx_setup cli command

- lr-cli/cortx_setup/commands/node/prepare/firewall.py
> EOS-20662: Field prepare Firewall configuration- debug logs added

- Vagrantfile
------------------------------------------------------------
- Fix for enclosure_id grain
- Fix to the Vagrantfile
> Fixes identified during HW deployment

- lr-cli/cortx_setup/api_spec.yaml
- lr-cli/cortx_setup/commands/__init__.py
- lr-cli/cortx_setup/commands/node/prepare/storage.py
- lr-cli/cortx_setup/commands/storage/commons.py
- lr-cli/cortx_setup/commands/storage/config.py
> EOS-20665: Field Prepare - Storage configuration

- api/python/provisioner/commands/check.py
- api/python/provisioner/commands/upgrade/sw_upgrade.py
- api/python/provisioner/config.py
I implemented logic to ensure that an active upgrade ISO is available.
Signed-off-by: Dmitry Didenko <dimitry.didenko@seagate.com>
> EOS-20676: [upgrade pre-validation] Ensure that an active upgrade ISO is available

- test/r2.md
-----
[View rendered test/r2.md](https://github.com/Seagate/cortx-prvsnr/blob/storageset-test-cases/test/r2.md)
> [Tests] Field: Storageset test case scenarios

- api/python/requirements/install.txt
> EOS-20788: Fix version for prerequistite requests package

- api/python/provisioner/commands/setup_provisioner.py
> EOS-20862:refresh pillar to update enclosure id

- api/python/provisioner/commands/deploy.py
- api/python/provisioner/commands/deploy_dual.py
- api/python/provisioner/commands/deploy_vm.py
> EOS-20580: Remove consul check for HA

- test/r2.md
-----
[View rendered test/r2.md](https://github.com/rahuljyoti65/cortx-prvsnr/blob/update_r2_md/test/r2.md)
> added test cases for field prepare - time configuration

- pillar/components/firewall.sls
> EOS-21068: Open port 80 on Management and Public Data ports

- api/python/provisioner/commands/configure_setup.py
- api/python/provisioner/commands/validator/config_sections.py
> EOS-20920: added validation for config.ini interfaces and devices

- lr-cli/cortx_setup/api_spec.yaml
- lr-cli/cortx_setup/commands/__init__.py
- lr-cli/cortx_setup/commands/cluster/config/network.py
- lr-cli/cortx_setup/commands/cluster/create.py
- lr-cli/cortx_setup/commands/network/config.py
- lr-cli/cortx_setup/commands/node/prepare/config.py
- lr-cli/cortx_setup/commands/node/prepare/network.py
- lr-cli/cortx_setup/commands/node/prepare/server.py
- lr-cli/cortx_setup/commands/node/prepare/storage.py
- lr-cli/cortx_setup/commands/node/prepare/time.py
- lr-cli/cortx_setup/commands/pillar_sync.py
- lr-cli/cortx_setup/commands/storage/config.py
- lr-cli/cortx_setup/commands/storageset/add/enclosure.py
- lr-cli/cortx_setup/commands/storageset/add/node.py
- lr-cli/cortx_setup/commands/storageset/config/durability.py
- lr-cli/cortx_setup/commands/storageset/create.py
- lr-cli/cortx_setup/config.py
- lr-cli/cortx_setup/log.py
Prereq : 
salt cluster should be configured. local data should be available on all nodes.
1. collect all pillar data from local and add in shared dir
` cortx_setup pillar_sync`
> [EOS-20908] Collect pillar data from all nodes

- devops/ci/multi_node_deploy/3node_deploy.jenkinsfile
- devops/ci/multi_node_deploy/3node_destroy.jenkinsfile
- devops/ci/single_node_deploy/deploy.jenkinsfile
- devops/ci/single_node_deploy/deploy_iso.jenkinsfile
- devops/ci/single_node_deploy/destroy.jenkinsfile
- pillar/components/firewall.sls
Below patch wasnt working as part of 3_node deploy job, provided a fix with this PR, Please review.
[root@ssc-vm-4662 ~]# device_list=$(lsblk -nd -o NAME -e 11|grep -v sda|sed 's|sd|/dev/sd|g'|paste -s -d, -)
[root@ssc-vm-4662 ~]# echo ${device_list%%,*}
/dev/sdb
[root@ssc-vm-4662 ~]# echo ${device_list#*,}
/dev/sdc,/dev/sdd,/dev/sde,/dev/sdf,/dev/sdg,/dev/sdh,/dev/sdi
> jenkins-fix: updated config.ini file config

- srv/components/system/firewall/config.sls
> EOS-21003: Remove port forwarding in firewall

- lr-cli/cortx_setup/commands/storage/commons.py
- lr-cli/cortx_setup/commands/storage/config.py
- lr-cli/cortx_setup/commands/storage/enclosure_info.py
> EOS-21101: lr-cli fetch enclosure_id from controller with plain password

- cli/src/factory_ops/unboxing/init
- cli/src/factory_ops/unboxing/pre_unbox
- docs/User-Guides/Deploy VM ISO Repo.md
- pillar/components/storage.sls
- srv/components/provisioner/salt_master/files/master
- srv/components/provisioner/salt_minion/files/minion
- srv/components/provisioner/salt_minion/files/minion_factory
- test/srv/components/system/config/test_setup_ssh_sls.py
-----
[View rendered docs/User-Guides/Deploy VM ISO Repo.md](https://github.com/Seagate/cortx-prvsnr/blob/EOS-19569/docs/User-Guides/Deploy VM ISO Repo.md)
> EOS-19569: Clarifying salt-master related strings

- lr-cli/cortx_setup/commands/node/prepare/time.py
> patch for time config failure in the absence of enclosure_id

- srv/components/misc_pkgs/rabbitmq/teardown.sls
> Fix for Destroy job

- srv/k8s/README.md
-----
[View rendered srv/k8s/README.md](https://github.com/Seagate/cortx-prvsnr/blob/k8s-doc/srv/k8s/README.md)
> Documentation for K8s use

- api/python/provisioner/commands/deploy.py
- api/python/provisioner/commands/destroy.py
- cli/src/virtual_appliance/bootstrap.sh
- srv/components/misc_pkgs/rabbitmq/teardown.sls
> EOS-21182: Remove rabbitmq from deployment and teardown

- api/python/provisioner/commands/deploy.py
- api/python/provisioner/commands/destroy.py
- cli/src/virtual_appliance/bootstrap.sh
- srv/components/misc_pkgs/rabbitmq/teardown.sls
- srv/k8s/README.md
-----
[View rendered srv/k8s/README.md](https://github.com/Seagate/cortx-prvsnr/blob/main-candidate-150621/srv/k8s/README.md)
> Main candidate 150621

- api/python/provisioner/commands/deploy.py
- api/python/provisioner/commands/destroy.py
- cli/src/virtual_appliance/bootstrap.sh
- srv/components/misc_pkgs/rabbitmq/teardown.sls
- srv/k8s/README.md
-----
[View rendered srv/k8s/README.md](https://github.com/Seagate/cortx-prvsnr/blob/stable-candidate-150621/srv/k8s/README.md)
> Stable candidate 150621

- pillar/components/commons.sls
- srv/components/misc_pkgs/elasticsearch/config.sls
- srv/components/misc_pkgs/elasticsearch/files/elasticsearch.yml.j2
- srv/components/misc_pkgs/elasticsearch/init.sls
- srv/components/misc_pkgs/elasticsearch/install.sls
- srv/components/misc_pkgs/elasticsearch/prepare.sls
- srv/components/misc_pkgs/elasticsearch/teardown.sls
- srv/components/misc_pkgs/kibana/config.sls
- srv/components/misc_pkgs/kibana/files/kibana.yml.j2
- srv/components/misc_pkgs/kibana/init.sls
- srv/components/misc_pkgs/kibana/install.sls
- srv/components/misc_pkgs/kibana/teardown.sls
- srv/components/system/files/cortx_py_utils_requirements.txt
Opendistro internally has a direct dependency on elasticsearch-oss.
Thus, the original problem is unaddressed. Hence, putting this PR on hold.
> EOS-19470: Elasticsearch and Kibana deployment using Opendistro

- api/python/provisioner/commands/check.py
- api/python/provisioner/commands/upgrade/get_iso_version.py
- api/python/provisioner/commands/upgrade/get_swupgrade_info.py
- api/python/provisioner/commands/upgrade/set_swupgrade_repo.py
- api/python/provisioner/config.py
- test/api/python/provisioner/test_sw_upgrade.py
I added validation to ensure that there is no active upgrade ISO available
> EOS-20677: Ensure that no active upgrade ISO is available

- api/python/provisioner/commands/upgrade/remove_swupgrade_repo.py
Extend API lock for **remove_swupgrade_repo** command
> EOS-20678: Ensure that upgrade is not running

- api/python/provisioner/__metadata__.py
- api/python/provisioner/commands/upgrade/sw_upgrade.py
- api/python/provisioner/config.py
- api/python/provisioner/cortx_ha.py
Starts using new HA interfaces
> [EOS-20783][EOS-20784] adds usage for new HA interfaces

- devops/jenkins/cortx_jenkins/jobs.py
> fixed bug in cortx-jenkins job command

- devops/ci/single_node_deploy/deploy.jenkinsfile
> Fix for jenkins deploy job failure

- devops/ci/multi_node_deploy/3node_deploy.jenkinsfile
> Fix for 3 node deployment, missed earlier

- srv/components/misc_pkgs/kafka/config.sls
> EOS-21185: Increase replication factor for 3-node kafka cluster

- lr-cli/cortx_setup/api_spec.yaml
- lr-cli/cortx_setup/commands/__init__.py
- lr-cli/cortx_setup/commands/node/initialize.py
- lr-cli/cortx_setup/commands/node/prepare/network.py
- pillar/components/execution.sls
> EOS-21227: Improvements - Factory and Field process

- lr-cli/cortx_setup/commands/security/config.py
- lr-cli/cortx_setup/config.py
- lr-cli/cortx_setup/validate.py
1. It will validate if path is present
2. Validate if file is cert
3.  If certificate is expired
> certificate installation command

- api/python/provisioner/__metadata__.py
- api/python/provisioner/commands/upgrade/check_iso_authenticity.py
- api/python/provisioner/commands/upgrade/get_swupgrade_info.py
- api/python/provisioner/commands/validator/validator.py
Convert explicitly GPG public key to OpenPGP format. I added some minor fixes and improvements
> EOS-19965: [SW_UPGRADE][HOT_FIX]: GPG signature validation fix & other minor fixes

- devops/ci/multi_node_deploy/3node_destroy.jenkinsfile
- devops/ci/single_node_deploy/destroy.jenkinsfile
> remove processes in teardown

- lr-cli/cortx_setup/api_spec.yaml
- lr-cli/cortx_setup/commands/__init__.py
- lr-cli/cortx_setup/commands/command.py
- lr-cli/cortx_setup/commands/pillar_sync.py
- lr-cli/cortx_setup/commands/salt_cleanup.py
> [EOS-21202] API to cleanup local salt configuration

- devops/ci/multi_node_deploy/3node_destroy.jenkinsfile
- devops/ci/single_node_deploy/destroy.jenkinsfile
> Merge #1394 regression addressed

- lr-cli/cortx_setup/commands/node/prepare/software.py
- srv/components/system/network/mgmt/ip_alias/init.sls
> EOS-21265: NodePrepare improvements to field deployment process.

- lr-cli/cortx_setup/api_spec.yaml
- lr-cli/cortx_setup/commands/__init__.py
- lr-cli/cortx_setup/commands/node/prepare/storage.py
- lr-cli/cortx_setup/commands/node/prepare/time.py
- lr-cli/cortx_setup/commands/server/__init__.py
- lr-cli/cortx_setup/commands/server/config.py
- lr-cli/cortx_setup/commands/storage/config.py
- lr-cli/cortx_setup/commands/storage/enclosure_info.py
> EOS-21287, EOS-21227, EOS-21197: lr-cli factory server config and factory storage config for vm

- lr-cli/cortx_setup/commands/cluster/create.py
> [EOS-21368] removed default values for create cluster command

- api/python/provisioner/commands/configure_setup.py
- api/python/provisioner/commands/validator/config_sections.py
> EOS-21421 : updated config.ini validations for data and matadata devices

- test/r2.md
-----
[View rendered test/r2.md](https://github.com/nayakkishan/cortx-prvsnr/blob/test_result_sprint_45/test/r2.md)
> Update test results for sprint-45/46

- devops/ci/multi_node_deploy/3node_destroy.jenkinsfile
- devops/ci/single_node_deploy/destroy.jenkinsfile
- srv/_modules/cortx_unsupported_features.py
- srv/components/csm/config/config.sls
- test/r2.md
> EOS-19686: Logic incorporated for unsupported feature

- api/python/provisioner/commands/configure_setup.py
- api/python/provisioner/commands/validator/config_sections.py
- devops/ci/multi_node_deploy/3node_destroy.jenkinsfile
- devops/ci/single_node_deploy/destroy.jenkinsfile
- lr-cli/cortx_setup/api_spec.yaml
- lr-cli/cortx_setup/commands/__init__.py
- lr-cli/cortx_setup/commands/cluster/create.py
- lr-cli/cortx_setup/commands/node/prepare/software.py
- lr-cli/cortx_setup/commands/node/prepare/storage.py
- lr-cli/cortx_setup/commands/node/prepare/time.py
- lr-cli/cortx_setup/commands/pillar_sync.py
- lr-cli/cortx_setup/commands/salt_cleanup.py
- lr-cli/cortx_setup/commands/server/__init__.py
- lr-cli/cortx_setup/commands/server/config.py
- lr-cli/cortx_setup/commands/storage/config.py
- lr-cli/cortx_setup/commands/storage/enclosure_info.py
- srv/_modules/cortx_unsupported_features.py
- srv/components/csm/config/config.sls
- srv/components/system/network/mgmt/ip_alias/init.sls
- test/r2.md
-----
[View rendered test/r2.md](https://github.com/Seagate/cortx-prvsnr/blob/main-candidate-22-6-2021/test/r2.md)
> Main candidate 22 6 2021

- api/python/provisioner/commands/bootstrap_provisioner.py
- api/python/provisioner/commands/cluster_id.py
- api/python/provisioner/commands/setup_provisioner.py
- docs/design_updates.md
- lr-cli/cortx_setup/api_spec.yaml
- lr-cli/cortx_setup/commands/__init__.py
- lr-cli/cortx_setup/commands/cluster/config/component.py
- lr-cli/cortx_setup/commands/cluster/config/network.py
- lr-cli/cortx_setup/commands/cluster/create.py
- lr-cli/cortx_setup/commands/cluster/generate.py
- lr-cli/cortx_setup/commands/cluster/show.py
- lr-cli/cortx_setup/commands/common_utils.py
- lr-cli/cortx_setup/commands/storageset/add/enclosure.py
- lr-cli/cortx_setup/commands/storageset/add/node.py
- lr-cli/cortx_setup/config.py
> EOS-21207: Enhancements after integration of Field APIs

- lr-cli/cortx_setup/api_spec.yaml
- lr-cli/cortx_setup/commands/__init__.py
- lr-cli/cortx_setup/commands/confstore.py
- srv/components/system/files/factory_confstore_template.j2
> EOS-21916: Factory: Missing Mini-Provisioner ConfStore default keys

- api/python/provisioner/commands/deploy.py
- api/python/provisioner/commands/deploy_dual.py
- api/python/provisioner/commands/deploy_jbod.py
- api/python/provisioner/commands/deploy_vm.py
- api/python/provisioner/commands/destroy.py
- api/python/provisioner/config.py
- pillar/components/commons.sls
- srv/components/misc_pkgs/init.sls
> EOS-21920 : remove rabbitmq from all deploy files

- api/python/provisioner/commands/cluster_id.py
- api/python/provisioner/commands/setup_provisioner.py
- srv/_grains/cluster-id.py
> EOS-21413 : updated cluster-id logic

- api/python/provisioner/utils.py
- devops/jenkins/MANIFEST.in
- devops/jenkins/README.md
- devops/jenkins/cortx_jenkins/__main__.py
- devops/jenkins/cortx_jenkins/__metadata__.py
- devops/jenkins/cortx_jenkins/agent.py
- devops/jenkins/cortx_jenkins/agent/Dockerfile.inbound-agent
- devops/jenkins/cortx_jenkins/agent/trust_server.sh
- devops/jenkins/cortx_jenkins/cortx-jenkins.toml.example
- devops/jenkins/cortx_jenkins/jobs/cortx-prvsnr/cortx-prvsnr-jobs.yaml
- devops/jenkins/cortx_jenkins/jobs/defaults.yaml
- devops/jenkins/cortx_jenkins/server.py
- devops/jenkins/cortx_jenkins/server/jenkins.yaml.tmpl
- devops/jenkins/cortx_jenkins/utils.py
- test/api/python/provisioner/test_utils.py
-----
[View rendered devops/jenkins/README.md](https://github.com/andkononykhin2/cortx-prvsnr/blob/EOS-20974-provisioner-production-ci/devops/jenkins/README.md)
> EOS-20974: adds docs for jenkins automation

- api/python/provisioner/commands/configure_setup.py
- api/python/provisioner/commands/validator/config_sections.py
- devops/ci/multi_node_deploy/3node_destroy.jenkinsfile
- devops/ci/single_node_deploy/destroy.jenkinsfile
- lr-cli/cortx_setup/api_spec.yaml
- lr-cli/cortx_setup/commands/__init__.py
- lr-cli/cortx_setup/commands/cluster/create.py
- lr-cli/cortx_setup/commands/node/prepare/software.py
- lr-cli/cortx_setup/commands/node/prepare/storage.py
- lr-cli/cortx_setup/commands/node/prepare/time.py
- lr-cli/cortx_setup/commands/pillar_sync.py
- lr-cli/cortx_setup/commands/salt_cleanup.py
- lr-cli/cortx_setup/commands/server/__init__.py
- lr-cli/cortx_setup/commands/server/config.py
- lr-cli/cortx_setup/commands/storage/config.py
- lr-cli/cortx_setup/commands/storage/enclosure_info.py
- srv/_modules/cortx_unsupported_features.py
- srv/components/csm/config/config.sls
- srv/components/system/network/mgmt/ip_alias/init.sls
- test/r2.md
-----
[View rendered test/r2.md](https://github.com/Seagate/cortx-prvsnr/blob/stable-candidate-24-06-2021/test/r2.md)
> Stable candidate 24 06 2021

- lr-cli/cortx_setup/commands/cluster/create.py
- lr-cli/cortx_setup/commands/cluster/generate.py
> EOS-20030: bootstrap minor changes for robustness

- lr-cli/cortx_setup/commands/cluster/config/network.py
Add support for mgmt_vip in cluster network
> [MGMT_VIP] add support for mgmt_vip in cluster network

- api/python/provisioner/commands/bootstrap_provisioner.py
- lr-cli/cortx_setup/commands/cluster/create.py
- lr-cli/cortx_setup/commands/node/prepare/time.py
- lr-cli/cortx_setup/commands/storage/config.py
- srv/components/controller/ntp.sls
> EOS-21961: addressed minor bootstrap and ntp issues

- lr-cli/cortx_setup/commands/cluster/config/network.py
- lr-cli/cortx_setup/commands/cluster/create.py
> [MGMT_VIP] fixed management vip and  dns server 

- lr-cli/cortx_setup/commands/cluster/config/component.py
- lr-cli/cortx_setup/commands/cluster/prepare.py
> Changes to cluster prepare and config wrt prerequisite states

- lr-cli/cortx_setup/api_spec.yaml
- lr-cli/cortx_setup/commands/__init__.py
- lr-cli/cortx_setup/commands/node/prepare/finalize.py
Wrapper around salt cleanup command
> [NodePrepareFinalize] wrapper of salt cleanup command

- api/python/provisioner/commands/bootstrap_provisioner.py
- api/python/provisioner/commands/cluster_id.py
- lr-cli/cortx_setup/commands/cluster/create.py
- lr-cli/cortx_setup/commands/cluster/prepare.py
- lr-cli/cortx_setup/commands/node/prepare/time.py
- lr-cli/cortx_setup/commands/storage/config.py
- pillar/components/execution.sls
- srv/_grains/enclosure.py
> EOS-21921: addressed integration issues

- api/python/provisioner/commands/check.py
- api/python/provisioner/commands/upgrade/sw_upgrade.py
- api/python/provisioner/config.py
I added post-validations for SW upgrade.
> EOS-19962: Review and activate pre validations for disruptive upgrade of CORTX SW

- lr-cli/cortx_setup/commands/storage/config.py
Two changes
1. Increment cvg_count by 1 with each successful run of 'storage config' command with 'cvg' option.
2. User data type of cvg_count as int for Pillar and as string for confstore
> Increment cvg_count by 1 with each successful run of 'storage config' command with 'cvg' option.

- lr-cli/cortx_setup/commands/cluster/config/component.py
> [EOS-20036] run ha component in sequence primary and then secondaries

- lr-cli/cortx_setup/commands/node/initialize.py
> [Fix] Sync salt data in pillar 

- srv/components/provisioner/scripts/cortx_prep.sh
> Add missing cortx packages

- api/python/provisioner/__metadata__.py
- api/python/provisioner/api.py
- api/python/provisioner/commands/upgrade/check_iso_authenticity.py
- api/python/provisioner/commands/upgrade/set_swupgrade_repo.py
- test/api/python/provisioner/test_sw_upgrade.py
I added necessary pre-validation for the set SW upgrade, I made the signature validation mandatory.
> EOS-19961: Review and activate pre validations for disruptive upgrade of CORTX SW

- api/python/provisioner/commands/check.py
Improve communicability check for SW upgrade
> [SW_Upgrade]: Improve communicability check for SW upgrade

- lr-cli/cortx_setup/commands/network/config.py
```
cortx_setup network config --mode tcp --transport lnet
```
> [Fix_transport_mode] Support for transport param in  network config

- lr-cli/cortx_setup/commands/resource/discover.py
> [Codacy_Fix]fix codacy issue

- lr-cli/cortx_setup/commands/cluster/create.py
- lr-cli/cortx_setup/commands/storageset/add/enclosure.py
- lr-cli/cortx_setup/commands/storageset/create.py
> [Fix storage data] Integration issue: move storage file on all nodes

- api/python/provisioner/srv/salt/provisioner/configure_salt_minion.sls
cleanup salt-minion id if already exist
> [Fix_LR_CLI] Fix cluster id issue in cluster create command

- srv/components/provisioner/scripts/cortx_prep.sh
Update CORTX prep script with:
1. Install missing packages
2. Gracefully handle errors
3. Improvise logging
> Update CORTX prep script

- lr-cli/cortx_setup/commands/storage/config.py
- srv/components/provisioner/scripts/cortx_prep.sh
> Fix codacy issue

- srv/components/provisioner/scripts/cortx_prep.sh
1. wait for scsi-network-relay service to load
2. Add the updated PATH variable in .bashrc
3. Add CORTX_RELEASE_REPO variable to .bashrc
> Fix startup script issues:

- api/python/provisioner/commands/cluster_id.py
- api/python/provisioner/commands/confstore_export.py
- lr-cli/cortx_setup/commands/cluster/create.py
- lr-cli/cortx_setup/commands/cluster/generate.py
> updated cluster_id Issue for cortx_setup

- srv/components/csm/start.sls
- srv/components/misc_pkgs/kibana/stop.sls
> EOS-21409: removed enable from kibana and csm as pcs enables services

- devops/ci/single_node_deploy/deploy.jenkinsfile
- devops/ci/single_node_deploy/deploy_iso.jenkinsfile
And set the mgmt_vip to None in config.ini
> Remove MGMT_VIP option jenkinsfile for single node deployment

- api/python/provisioner/commands/configure_setup.py
> [EOS-22167] Support additional comma in config.ini values

- lr-cli/README.md
-----
[View rendered lr-cli/README.md](https://github.com/Seagate/cortx-prvsnr/blob/cortx_setup_doc/lr-cli/README.md)
> [doc] Cortx setup commands README 

- pillar/components/execution.sls
- srv/components/csm/config/config.sls
> EOS-22261: addressed 3-node vm deployment issues for cortx_setup API

- lr-cli/cortx_setup/commands/storage/config.py
> EOS-22258: Added Validation check in case of blank in device list

- lr-cli/cortx_setup/commands/node/finalize.py
> Fixing node finalize for health map validation

- devops/rpms/lr-cli/build_python_cortx_setup.sh
- lr-cli/install_scripts/post_setup.sh
- lr-cli/install_scripts/pre_setup.sh
> Create separate package for lr-cli, cortx_setup commands.

- devops/rpms/lr-cli/build_python_cortx_setup.sh
cortx-setup package generation- remove quotes from "iteration" variable in fpm command
> cortx-setup package generation- remove quotes from "iteration" variable in fpm command

- api/python/provisioner/commands/configure_setup.py
- devops/ci/single_node_deploy/deploy.jenkinsfile
- devops/ci/single_node_deploy/deploy_iso.jenkinsfile
- devops/rpms/lr-cli/build_python_cortx_setup.sh
- lr-cli/README.md
- lr-cli/cortx_setup/commands/node/finalize.py
- lr-cli/cortx_setup/commands/storage/config.py
- lr-cli/install_scripts/post_setup.sh
- lr-cli/install_scripts/pre_setup.sh
- lr-cli/setup.py
- pillar/components/execution.sls
- srv/components/csm/config/config.sls
-----
[View rendered lr-cli/README.md](https://github.com/Seagate/cortx-prvsnr/blob/main-candidate-9-7-21/lr-cli/README.md)
> Main candidate 9 7 21

- api/python/provisioner/commands/configure_setup.py
- devops/ci/single_node_deploy/deploy.jenkinsfile
- devops/ci/single_node_deploy/deploy_iso.jenkinsfile
- devops/rpms/lr-cli/build_python_cortx_setup.sh
- lr-cli/README.md
- lr-cli/cortx_setup/commands/node/finalize.py
- lr-cli/cortx_setup/commands/storage/config.py
- lr-cli/install_scripts/post_setup.sh
- lr-cli/install_scripts/pre_setup.sh
- lr-cli/setup.py
- pillar/components/execution.sls
- srv/components/csm/config/config.sls
-----
[View rendered lr-cli/README.md](https://github.com/Seagate/cortx-prvsnr/blob/stable-candidate-9-7-21/lr-cli/README.md)
> Stable candidate 9 7 21

- lr-cli/cortx_setup/commands/node/prepare/network.py
Signed-off-by: zahid.shaikh <zahid.shaikh@seagate.com>
> EOS-22276 default values removed for dns_servers and search_domains

- lr-cli/cortx_setup/commands/resource/show.py
> EOS-22947: Fix resource show api in irrespective of case in health status

- lr-cli/cortx_setup/commands/resource/show.py
> EOS-22953: Fix resourcemap show health in case of no resource type specified.

- lr-cli/cortx_setup/commands/cluster/config/network.py
- lr-cli/cortx_setup/commands/cluster/create.py
- lr-cli/cortx_setup/commands/command.py
- lr-cli/cortx_setup/commands/node/prepare/config.py
- lr-cli/cortx_setup/commands/node/prepare/firewall.py
- lr-cli/cortx_setup/commands/node/prepare/network.py
- lr-cli/cortx_setup/commands/node/prepare/storage.py
- lr-cli/cortx_setup/commands/storageset/add/enclosure.py
- lr-cli/cortx_setup/commands/storageset/add/node.py
- lr-cli/cortx_setup/commands/storageset/config/durability.py
- lr-cli/cortx_setup/commands/storageset/create.py
> [Fix] Fix confstore load issue in cortx setup commands

- node_cli/schema/storageset.json
> EOS-20028: Field - Cluster Definition using NodeAdmin CLI

- node_cli/schema/node.json
> EOS-20027: Field - Node Preparation using NodeAdmin CLI

- node_cli/schema/cluster.json
> EOS-22263: Field - Cluster Startup using NodeAdmin CLI

- lr-cli/cortx_setup/commands/node/finalize.py
> EOS-22267: Create users as part of node finalize

- api/python/provisioner/commands/create_user.py
- devops/rpms/node_cli/node_cli.spec
- lr-cli/cortx_setup/commands/node/finalize.py
- lr-cli/cortx_setup/config.py
> EOS-22267: manage users' permissions

- lr-cli/cortx_setup/commands/cluster/config/network.py
- lr-cli/cortx_setup/commands/cluster/create.py
- lr-cli/cortx_setup/commands/storageset/add/enclosure.py
- lr-cli/cortx_setup/commands/storageset/add/node.py
- lr-cli/cortx_setup/commands/storageset/config/durability.py
- lr-cli/cortx_setup/commands/storageset/create.py
> updated confstore index conflict for captive nodecli

- lr-cli/cortx_setup/commands/signature/set.py
- lr-cli/cortx_setup/main.py
> [EOS-22958] User msg should be displayed for exceptions

- lr-cli/cortx_setup/commands/config/set.py
- srv/components/provisioner/scripts/install.sh
> EOS-22890: Fix install.sh: Provide absolute path of nodejs tar file

- lr-cli/cortx_setup/commands/storageset/add/enclosure.py
- lr-cli/cortx_setup/commands/storageset/add/node.py
- lr-cli/cortx_setup/commands/storageset/config/durability.py
- lr-cli/cortx_setup/commands/storageset/create.py
> EOS-20028: updated confstore index for updating storageset data

- lr-cli/cortx_setup/commands/cluster/create.py
- lr-cli/cortx_setup/commands/storageset/add/enclosure.py
- lr-cli/cortx_setup/commands/storageset/add/node.py
- lr-cli/cortx_setup/commands/storageset/config/durability.py
- lr-cli/cortx_setup/commands/storageset/create.py
> EOS-20028: updated confstore issue for storageset commands

- lr-cli/cortx_setup/commands/cluster/create.py
- lr-cli/cortx_setup/commands/storageset/add/enclosure.py
- lr-cli/cortx_setup/commands/storageset/add/node.py
- lr-cli/cortx_setup/commands/storageset/config/durability.py
- lr-cli/cortx_setup/commands/storageset/create.py
> EOS-20028: Fix Codacy issues

- srv/components/system/files/confstore_template.j2
> EOS-23141 : updated confstore keys for s3 requirements

- srv/components/system/files/confstore_template.j2
> EOS-23141 : updated confstore keys for s3 requirements (#5996)

- lr-cli/cortx_setup/commands/node/finalize.py
- node_cli/config.py
> EOS-22267: requirement update - support user to login directly inside nodecli

- srv/components/system/files/confstore_template.j2
> EOS-23154 : addressed syntax error

- api/python/provisioner/commands/bootstrap_provisioner.py
- lr-cli/cortx_setup/commands/cluster/create.py
- lr-cli/cortx_setup/config.py
- srv/components/provisioner/scripts/install.sh
> EOS-23179: cluster create: add support for iso

- lr-cli/cortx_setup/commands/storageset/config/durability.py
- srv/components/system/files/confstore_template.j2
Signed-off-by: zahid.shaikh <zahid.shaikh@seagate.com>
> EOS-22259 Populate DIX Pool layout parameters to confstore file

- lr-cli/cortx_setup/commands/node/finalize.py
- lr-cli/cortx_setup/commands/resource/discover.py
- lr-cli/cortx_setup/commands/resource/show.py
> EOS-23125: Extend Node CLI Support to Node Manifest View

- api/python/provisioner/commands/bootstrap_provisioner.py
- devops/ci/multi_node_deploy/3node_deploy.jenkinsfile
- lr-cli/cortx_setup/commands/cluster/config/component.py
- lr-cli/cortx_setup/commands/cluster/create.py
- lr-cli/cortx_setup/commands/node/finalize.py
- lr-cli/cortx_setup/commands/pillar_sync.py
- lr-cli/cortx_setup/commands/resource/discover.py
- lr-cli/cortx_setup/commands/resource/show.py
- lr-cli/cortx_setup/commands/storageset/config/durability.py
- lr-cli/cortx_setup/config.py
- srv/components/provisioner/confstore_copy.sls
- srv/components/provisioner/confstore_create.sls
- srv/components/provisioner/files/cluster_sls.template
- srv/components/provisioner/scripts/install.sh
- srv/components/system/files/confstore_template.j2
Commits:
**EOS-23179: cluster create: add support for iso
EOS-22259 Populate DIX Pool layout parameters to confstore file
EOS-23243 fix for confstore create failed intermittent issue
EOS-23125: Extend Node CLI Support to Node Manifest View**
> Push Main-Candidate-30July21 to Main

- lr-cli/cortx_setup/commands/cluster/create.py
- lr-cli/cortx_setup/commands/storage/config.py
- lr-cli/cortx_setup/commands/storageset/config/durability.py
- srv/components/provisioner/files/cluster_sls.template
- srv/components/system/files/confstore_template.j2
1. Rename data_devices to data-devices
2. Rename metadata_devices to metadata-devices
> EOS-22847: Supply DG to CVG mapping to SSPL

- api/python/provisioner/ssh.py
- lr-cli/cortx_setup/commands/cluster/create.py
> EOS-23413: Cluster create command failed in nodecli framework

- srv/components/provisioner/scripts/install.sh
- srv/components/system/files/confstore_template.j2
> EOS-23329: Update cluster name in confstore with correct pillar key

- node_cli/config.py
- node_cli/schema/resource.json
> EOS-20215: Captive Node CLI Command to generate Node Manifest

- lr-cli/cortx_setup/commands/pillar_sync.py
> Authenticate user onlyif passed through kwargs

- srv/components/system/files/confstore_template.j2
> EOS-23329: Improvised fix to set cluster name in confstore based on pillar availability

- api/python/provisioner/commands/bootstrap/provisioner_init.py
> EOS-23534: Create provisioner profile directory with UUID as a name

- lr-cli/cortx_setup/commands/storageset/add/enclosure.py
- lr-cli/cortx_setup/commands/storageset/add/node.py
- lr-cli/cortx_setup/commands/storageset/config/durability.py
- lr-cli/cortx_setup/commands/storageset/create.py
- srv/components/provisioner/files/cluster_sls.template
- srv/components/system/files/confstore_template.j2
This reverts commit 1de84310c89ac7c8e38d1e2e765e7680eb018223.
> Revert "EOS-23606: Add support to add more than 3 nodes in storage set

- lr-cli/cortx_setup/commands/storageset/add/enclosure.py
- lr-cli/cortx_setup/commands/storageset/add/node.py
- lr-cli/cortx_setup/commands/storageset/config/durability.py
- lr-cli/cortx_setup/commands/storageset/create.py
- srv/components/provisioner/files/cluster_sls.template
- srv/components/system/files/confstore_template.j2
> EOS-23606: Add support to add more than 3 nodes in a storage set

- api/python/provisioner/commands/bootstrap_provisioner.py
> EOS-24654: Create glob for target minions instead of string of concatenated minion ids

- api/python/provisioner/commands/bootstrap_provisioner.py
- api/python/provisioner/srv/salt/provisioner/configure_salt_master.sls
- pillar/components/firewall.sls
- srv/components/provisioner/salt_master/config.sls
- srv/components/provisioner/salt_master/files/master
- srv/components/provisioner/salt_master/files/master_factory
- srv/components/provisioner/scripts/install.sh
- srv/components/system/firewall/files/firewall_config.yaml
Signed-off-by: Lakshita Jain <lakshita.jain@seagate.com>
> EOS-23433: Firewall configuration updated with all services and ports

- README.md
-----
[View rendered README.md](https://github.com/83bhp/cortx-prvsnr/blob/EOS-xxx12/README.md)
> EOS-xxx12: Sample change for forked repo

- .github/pull_request_template.md
-----
[View rendered .github/pull_request_template.md](https://github.com/Seagate/cortx-prvsnr/blob/PR-template/.github/pull_request_template.md)
> Add template for Pull requests

- jenkins/docker/dockerfile
- Fix dependency packages  installation issue for cortx-provisioner dockerfile.
- 
-  Have added dependency packages installation inside dockerfile for working cortx-setup commands.
> Dockerfile fix

- conf/cluster.yaml.sample
- conf/config.yaml.sample
- src/provisioner/cluster.py
- src/provisioner/config.py
- src/provisioner/provisioner.py
- src/setup/cortx_setup.py
- test/deploy/k8s/cluster.yaml
- test/deploy/k8s/config.yaml
- test/deploy/k8s/cortx-pod-data.yml
- test/setup/README
- test/setup/cluster.yaml
- test/setup/config.yaml
- test/setup/test_setup.py
- cortx_setup config apply
Convert configmap to CORTX confstor.
> EOS-24425: cortx_setup config apply

- conf/config.yaml.sample
- src/provisioner/provisioner.py
- test/deploy/k8s/config.yaml
- test/setup/config.yaml
- test/setup/test_invalid_cluster_config.py
- test/setup/test_invalid_cortx_conf.py
- test/setup/test_multiple_storage_sets.py
- test/setup/test_provisioner.py
- test/setup/test_setup.py
- EOS-24425: config_apply
- Added unittest. 
- Fixed test_setup.py issue. 
- Removed lyve-cloud references from config.yaml files.
> EOS-24425: config_apply - Added unittests.

- src/provisioner/provisioner.py
- src/setup/cortx_setup.py
- test/deploy/k8s/cortx-deployment.yml
- test/deploy/k8s/cortx-pod-data.yml
- test/deploy/k8s/cortx-statefulset.yml
- test/setup/README
- test/setup/test_provisioner.py
- test/setup/test_setup.py
Signed-off-by: Selvakumar <selva.k.nambi@seagate.com>
- cortx_setup cluster bootstrap
Invoke MiniProvisioner interfaces such as post_install, prepare, config, init
-  https://jts.seagate.com/browse/EOS-24424
> EOS-24424: cortx_setup cluster bootstrap

- src/provisioner/provisioner.py
- test/deploy/k8s/config.yaml
- test/deploy/k8s/cortx-secret.yml
- test/deploy/k8s/cortx-statefulset.yml
- Accept Secret from ConfigMap and Decrypt from within container
Take Confidential value encrypt using cluster ID+Component ID and store onto conf store.
> Eos 24915 2: Added Source Code for Encryption of Secret Key

- jenkins/build.sh
- src/__init__.py
- src/provisioner/__init__.py
- src/provisioner/cluster.py
- src/provisioner/config.py
- src/provisioner/log.py
- src/provisioner/provisioner.py
- src/setup/cortx_setup.py
cortx setup shim: Add logging and validation
Test Result:
```
[root@ssc-vm-rhev4-1125 cortx-prvsnr-1]# ./test/setup/test_provisioner.py
2021-09-16 09:42:00 cortx_setup [1090827]: INFO [config_apply] Applying config yaml:///root/shim_EOS-24426_v1/cortx-prvsnr-1/test/setup/cluster.yaml
2021-09-16 09:42:00 cortx_setup [1090827]: INFO [cluster_bootstrap] Starting cluster bootstrap on 1:pod-1
2021-09-16 09:42:00 cortx_setup [1090827]: INFO [cluster_bootstrap] motr_setup --config yaml:///tmp/test_conf_store.conf --services all
2021-09-16 09:42:00 cortx_setup [1090827]: INFO [cluster_bootstrap] s3_setup --config yaml:///tmp/test_conf_store.conf --services all
2021-09-16 09:42:00 cortx_setup [1090827]: INFO [cluster_bootstrap] utils_setup --config yaml:///tmp/test_conf_store.conf --services all …
```
> EOS-24426: cortx_setup shim - add logging and validation

- jenkins/docker/dockerfile
- test/deploy/k8s/deploy.sh
> EOS-24432:  updated deploy.sh to support multiple pods logs

- test/deploy/k8s/deploy.sh
> quotes-fix added for dpeloy.sh script

- src/provisioner/provisioner.py
Signed-off-by: Selvakumar <selva.k.nambi@seagate.com>
- https://jts.seagate.com/browse/EOS-24978
-  Fix the missing keys in cluster.conf
> EOS-24978: Update cluster.conf keys

- .github/pull_request_template.md
- .github/workflows/alex_reviewdog.yml
- api/python/provisioner/commands/bootstrap_provisioner.py
- api/python/provisioner/srv/salt/provisioner/configure_salt_master.sls
- pillar/components/firewall.sls
- srv/components/provisioner/salt_master/config.sls
- srv/components/provisioner/salt_master/files/master_factory
- srv/components/provisioner/scripts/install.sh
- srv/components/system/firewall/files/firewall_config.yaml
-----
[View rendered .github/pull_request_template.md](https://github.com/Seagate/cortx-prvsnr/blob/stable-candidate-21-09-21/.github/pull_request_template.md)
> Stable candidate 21 09 21

- .github/pull_request_template.md
- .github/workflows/alex_reviewdog.yml
- api/python/provisioner/commands/bootstrap_provisioner.py
- api/python/provisioner/srv/salt/provisioner/configure_salt_master.sls
- pillar/components/firewall.sls
- srv/components/provisioner/salt_master/config.sls
- srv/components/provisioner/salt_master/files/master_factory
- srv/components/provisioner/scripts/install.sh
- srv/components/system/firewall/files/firewall_config.yaml
-----
[View rendered .github/pull_request_template.md](https://github.com/Seagate/cortx-prvsnr/blob/stable-candidate-21-09-21-new/.github/pull_request_template.md)
> Stable candidate 21 09 21 new

- conf/cluster.yaml.sample
- test/deploy/k8s/cluster.yaml
- test/setup/cluster.yaml
- test/setup/config.yaml
- Change cvg_type to 'ios' in cluster.yaml.
> Update cluster config- changed cvg_type to 'ios'.

- api/python/provisioner/commands/bootstrap_provisioner.py
- api/python/provisioner/srv/salt/provisioner/configure_salt_master.sls
- pillar/components/firewall.sls
- srv/components/provisioner/salt_master/config.sls
- srv/components/provisioner/salt_master/files/master_factory
- srv/components/provisioner/scripts/install.sh
- srv/components/system/firewall/files/firewall_config.yaml
-Merge the main branch to kubernetes
> Rebase kubernetes branch to main

- conf/config.yaml.sample
- src/provisioner/provisioner.py
- test/deploy/kubernetes/solution-config/config.yaml
- Fix for adding cluster>id in confstor.
> Add fix for cluster_id

- src/provisioner/cluster.py
- src/provisioner/provisioner.py
> Fix: Storage Storage Set as list in the generated Conf Store. 

- jenkins/build.sh
- setup.py
- src/provisioner/provisioner.py
- src/setup/cortx_deploy
- test/deploy/kubernetes/provisioner-pods/deployment_control_node.yaml
- test/deploy/kubernetes/provisioner-pods/deployment_storage_node1.yaml
- test/deploy/kubernetes/provisioner-pods/deployment_storage_node2.yaml
- test/deploy/kubernetes/provisioner-pods/deployment_storage_node3.yaml
- Develop Entrypoint script (cortx_deploy) for provisioner to be executed in kubernetes env
> EOS-24455: added entrypoint script for provisioner

- src/provisioner/provisioner.py
…store code
Signed-off-by: Kailash Yadav <kailash.yadav@seagate.com>
> Eos 24474 2 Changed key phrase 'cluster' to 'cortx' and modified cipher key store code

- src/setup/cortx_deploy
> fix for entrypoint provisioner script

- src/provisioner/provisioner.py
- RC is returned as 0 even if MiniProvisioner interfaces raises an exception
-  SimpleProcess got executed successfully, hence it returns rc as 0. So check/validate the error message as well. 
> Cluster Bootstrap: check/validate the error message

- devops/ci/multi_node_deploy/3node_deploy.jenkinsfile
- pillar/components/commons.sls
- pillar/components/cortx.sls
- pillar/components/execution.sls
- pillar/samples/config.ini
- pillar/samples/config_vm.ini
- srv/components/misc_pkgs/consul/config.sls
- srv/components/misc_pkgs/consul/init_mod.sls
- srv/components/misc_pkgs/consul/post_install.sls
- srv/components/misc_pkgs/consul/prepare.sls
- srv/components/provisioner/files/cluster_sls.template
- srv/components/system/files/confstore_template.j2
Signed-off-by: Satish Darade <satish.darade@seagate.com>
> EOS-24571: Consul-Integration-In-Prvsnr

- test/deploy/kubernetes/persistent-volumes/block_devices_node1.yaml
- test/deploy/kubernetes/persistent-volumes/block_devices_node2.yaml
- test/deploy/kubernetes/persistent-volumes/block_devices_node3.yaml
- test/deploy/kubernetes/provisioner-pods/deployment_storage_node1.yaml
- test/deploy/kubernetes/provisioner-pods/deployment_storage_node2.yaml
- test/deploy/kubernetes/provisioner-pods/deployment_storage_node3.yaml
- test/deploy/kubernetes/volume-claims/block_volumes_node1.yaml
- test/deploy/kubernetes/volume-claims/block_volumes_node2.yaml
- test/deploy/kubernetes/volume-claims/block_volumes_node3.yaml
Signed-off-by: Kailash <kailash.yadav@seagate.com>
> Eos 24474 4  Added Block device sde and removed sdj

- node_cli/schema/cluster.json
- node_cli/schema/node.json
> Updated default value of bool variables to false in cluster.json & node.json

- .whitesource
- CODEOWNERS
- README.md
-----
[View rendered README.md](https://github.com/Seagate/cortx-prvsnr/blob/stable-candidate-28-10-21/README.md)
> Stable candidate 28 10 21

- .whitesource
- CODEOWNERS
- README.md
- node_cli/schema/cluster.json
- node_cli/schema/node.json
-----
[View rendered README.md](https://github.com/Seagate/cortx-prvsnr/blob/stable-candidate-111121/README.md)
> Stable candidate 111121

- src/provisioner/provisioner.py
- src/setup/cortx_deploy
- src/setup/cortx_setup.py
- test/setup/test_provisioner.py
- test/setup/test_setup.py
-  Remove mock code  from provisioner script.
> EOS-26228: Remove mock code  from provisioner script.

- CODEOWNERS
- node_cli/schema/cluster.json
- node_cli/schema/node.json
> Kubernetes candidate

- .github/workflows/dco-check.yml
Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
DCO has encountered an issue with GitHub app and it's faced by all the projects which is reported in https://github.com/probot/dco/issues/162
-  N/A
> EOS-25933: DCO check workflow

- src/provisioner/provisioner.py
- src/setup/cortx_setup.py
- test/setup/cluster.yaml
- test/setup/config.yaml
- test/setup/test_provisioner.py
- test/setup/test_setup.py
- Implement cortx_setup upgrade command
-   cortx_setup upgrade will mock upgrade phase of all components
```
To validate the test cases please execute below before mocking bootstrap and upgrade.
mkdir -p /opt/seagate/cortx/motr/bin
mkdir -p /opt/seagate/cortx/s3/bin
mkdir -p /opt/seagate/cortx/hare/bin
mkdir -p /opt/seagate/cortx/csm/bin
mkdir -p /opt/seagate/cortx/utils/bin
nano /opt/seagate/cortx/motr/bin/motr_setup
#!/bin/bash
echo $*
chmod +x /opt/seagate/cortx/motr/bin/motr_setup;
cp -pf /opt/seagate/cortx/motr/bin/motr_setup /opt/seagate/cortx/s3/bin/s3_setup;
cp -pf /opt/seagate/cortx/motr/bin/motr_setup /opt/seagate/cortx/hare/bin/hare_setup;
cp -pf /opt/seagate/cortx/motr/bin/motr_setup /opt/seagate/cortx/csm/bin/csm_setup;
cp -pf /opt/seagate/cortx/motr/bin/motr_setup …
```
> EOS-26178: cortx_setup upgrade

- .github/workflows/dco-check.yml
Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
> dco check workflow (#6275)

- src/provisioner/provisioner.py
> Update version in confstore if upgrade is success.

- src/provisioner/release.py
-----
[View rendered experiments/logging/glusterfs/README.md](https://github.com/shriya-deshmukh/cortx-prvsnr-1/blob/fix_for_rpm_version/experiments/logging/glusterfs/README.md)
[View rendered experiments/logging/local/README.md](https://github.com/shriya-deshmukh/cortx-prvsnr-1/blob/fix_for_rpm_version/experiments/logging/local/README.md)
> Fix for rpm version

- src/provisioner/config.py
- src/provisioner/provisioner.py
- src/provisioner/release.py
-----
[View rendered experiments/logging/glusterfs/README.md](https://github.com/shriya-deshmukh/cortx-prvsnr-1/blob/fix-for-release-key/experiments/logging/glusterfs/README.md)
[View rendered experiments/logging/local/README.md](https://github.com/shriya-deshmukh/cortx-prvsnr-1/blob/fix-for-release-key/experiments/logging/local/README.md)
> Fix for 'cortx>common>release' key. 

- src/setup/cortx_deploy
Signed-off-by: Rahul Tripathi <rahul.tripathi@seagate.com>
- Added validations for image versions check
-  compared the versions present in confstore file and that present in cluste.conf file of the new image .
> EOS-26179: added validations for image versions in upgrade scenario

- src/setup/cortx_deploy
> Fix for cortx_deploy and added fix for data-pod.

- src/provisioner/provisioner.py
- Remove node_type hardcoded value ie. storage_node, data_node etc.
- Rearranging cvg list based on 'storage' key. 
> Fixed node_type hardcoded value.

- src/provisioner/provisioner.py
- src/setup/cortx_deploy
> Fix for deployment.

- src/provisioner/provisioner.py
- Validate only return code and remove check on STD_ERR as it stores additional information
-  MP has to return 0 on success and non zero on error.
> EOS-26755: Validate only return code and remove validations on STD_ERR

- src/provisioner/provisioner.py
- src/provisioner/validators.py
- Validation checks to ensure each component and service defined in cluster.yaml is supported in Utils const.py file.
-  Read component from cluster.yaml and verify it is present in const.py file.
- Read services list for component and verify service name is present in const.py file for that specific component.
> EOS-26878: Validation check for component and services.

- jenkins/docker/python_requirements.txt
- srv/components/system/files/cortx_py_utils_requirements.txt
- test-requirements.txt
PyYAML package needs to be upgraded to 5.4.1
JIRA Bug reference -> https://jts.seagate.com/browse/EOS-23696
Changes are to upgrade package version from 5.1.2 to 5.4.1
So coding conventions are not directly applicable
Testing conducted as follows
Code changes were made on all the repositories by creating forks.
Then it was build and deployed on single node cortx-k8s cluster
Then it was tested with automated sanity test
It was also tested for basic aws cli commands
Detailed test results are available at JIRA Bug -> https://jts.seagate.com/browse/EOS-23696
Checklist for …
> Upgrade pyyaml package to 5.4.1

- src/provisioner/cluster.py
- src/provisioner/config.py
- src/provisioner/config_store.py
- src/provisioner/provisioner.py
- src/provisioner/validators.py
- EOS-26898: Support for consul confstore.
> Use Full key path while fetching/saving key in confstore.(consul confstore support)

- conf/cluster.yaml.sample
- conf/config.yaml.sample
- test/deploy/kubernetes/solution-config/config.yaml
- test/deploy/kubernetes/template-config/cluster_redefined.yaml
> Update motr config parameter.

- conf/config.yaml.sample
> update endpoints in sample file.

- src/provisioner/provisioner.py
Signed-off-by: Lakshita Jain <lakshita.jain@seagate.com>
- Updated provisioner.py for secrets path variable name 
> EOS:27327: changed secrets path variable name

- CODEOWNERS
Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
- Removed Termed members as Codeowners
> Removed Termed members as Codeowners

- conf/gconf/cluster.conf.sample
- conf/solution/config.yaml.sample
- Update Solution config files from conf folder with updated confluence page.
> CORTX-27655: updated conf sample files

- conf/gconf/cluster.conf.sample
- conf/solution/config.yaml.sample
- CORTX-27655: Updated sample config files in rgw branch in sync with confluence pages.
> CORTX-27655: Updated sample config files in rgw branch in sync with confluence pages.

- conf/gconf/cluster.conf.sample
- conf/solution/config.yaml.sample
- CORTX-29590: Updated sample config files with latest changes
> CORTX-29590: Updated sample config files with latest changes

- setup.py
Signed-off-by: Kailash Yadav <kailash.yadav@seagate.com>
- Resolve codacy issues reported by codacy lynting tools
- [ For Bug, Describe the fix here.](https://jts.seagate.com/browse/CORTX-30247)
> CORTX-30247: Codacy Fix: commit 1

- .github/pull_request_template.md
- CODE_OF_CONDUCT.md
- README.md
- src/__init__.py
- src/provisioner/__init__.py
- src/provisioner/cluster.py
- src/provisioner/config.py
- src/provisioner/error.py
- src/provisioner/log.py
- src/provisioner/provisioner.py
- test/setup/test_setup.py
- address provisioner codacy errors mentioned in codacy dashboard
-  As part of this PR, most of the readme.md conventions, as well as a few python codacy errors, are addressed.
-----
[View rendered .github/pull_request_template.md](https://github.com/Seagate/cortx-prvsnr/blob/CORTX-30248/.github/pull_request_template.md)
[View rendered CODE_OF_CONDUCT.md](https://github.com/Seagate/cortx-prvsnr/blob/CORTX-30248/CODE_OF_CONDUCT.md)
[View rendered README.md](https://github.com/Seagate/cortx-prvsnr/blob/CORTX-30248/README.md)
> CORTX-30248: addressing codacy errors

- .github/pull_request_template.md
Signed-off-by: Zahid Shaikh <zahid.shaikh@seagate.com>
- Codecy fix - https://jts.seagate.com/browse/CORTX-30253
-   [x] Coding conventions are followed and code is consistent
-   [ ] Unit and System Tests are added
-   [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
-   [ ] Testing was performed with RPM
-   [ ] Interface change (if any) are documented
-   [ ] Side effects on other features (deployment/upgrade)
-   [ ] Dependencies on other component(s)
-   [x] JIRA number/GitHub Issue added to PR
-   [x] PR is self reviewed
-   [x] Jira and state/status is updated and JIRA is updated with PR …
> Codecy Fix - Markdown for pull_request_template.md

- setup.py
- src/provisioner/cluster.py
- src/provisioner/config.py
- src/provisioner/provisioner.py
Currently making Docstring related codacy error resolution
changes in the 4 files.
Signed-off-by: Lakshita Jain <lakshita.jain@seagate.com>
-   [x] Coding conventions are followed and code is consistent
-   [ ] Unit and System Tests are added
-   [x] Test Cases cover Happy Path, Non-Happy Path and Scalability
-   [x] Testing was performed with RPM
-   [ ] Interface change (if any) are documented
-   [ ] Side effects on other features (deployment/upgrade)
-   [ ] Dependencies on other component(s)
-   [x] JIRA number/GitHub Issue added to PR
-   [x] PR is self reviewed
-   [x] Jira and …
>  CORTX-30252: Docstring Codacy errors resolution

- jenkins/docker/python_requirements.txt
Signed-off-by: Swanand S Gadre <swanand.s.gadre@seagate.com>
Current cryptography version is 2.8. This version has High/medium level vulnerabilities
This version is planned to be upgraded to 3.3.2
Thought process of upgrading to version 3.3.2 is as follows
Version upgrade for cryptography library from version 2.8 to version 3.3.2 is recommended by Whitesource vulnerability scanning tool.
There are several cryptography versions available which are higher than 3.3.2. However further library package upgrade will be planned in subsequent iteration,
Reference to cryptography version to 3.3.2 is upgraded at following file
– Jenkins/docker/python_requirements.txt
-  [X] Coding …
> CORTX-29993 - Update cryptography library from 2.8 to 3.3.2

- conf/gconf/cluster.conf.sample
- conf/solution/config.yaml.sample
- test/setup/config.yaml
*   \[x] Interface change (if any) are documented
*   \[x] Jira and state/status is updated and JIRA is updated with PR link
*   \[x] Check if the description is clear and explained
Checklist for …
> Cortx 30792: Updating HA service endpoints in multiple files

- .github/pull_request_template.md
- CODE_OF_CONDUCT.md
- SECURITY.md
- jenkins/build.sh
- jenkins/docker/dockerfile
- src/provisioner/provisioner.py
CORTX-30255: Fix Codacy issues in provisioner
Fix issues mentioned in : https://app.codacy.com/gh/Seagate/cortx-prvsnr/issues for cleanup codacy errors
*   \[x] Jira and state/status is updated …
> CORTX-30255: Fix Codacy issues in provisioner

- jenkins/docker/dockerfile
*   Address codacy
*   \[x] Jira and state/status is updated and JIRA is updated with PR link
*   \[x] Check if the …
> CORTX-30255: address codacy errors

- src/provisioner/cluster.py
- src/provisioner/config.py
Signed-off-by: Zahid Shaikh <zahid.shaikh@seagate.com>
*   [CORTX-30256](https://jts.seagate.com/browse/CORTX-30256) CODACY tasks-Sprint69 
*   \[ ] JIRA number/GitHub Issue added to PR
*   \[ ] PR is self reviewed
*   \[ ] Jira and state/status is …
> Codecy fix: python function- Removed default value as list

- src/provisioner/cluster.py
Signed-off-by: Zahid Shaikh <zahid.shaikh@seagate.com>
- Merge "storage>cvg" hierarchy to "cvg" in GConf
> [WIP] CORTX-30761 Merge "storage>cvg" hierarchy to "cvg" in GConf

- src/provisioner/const.py
- src/provisioner/provisioner.py
* Update consul cortx conf with version details and save consul conf url at local pvc/empty dir, to be used later during version compatibility check by utils.
*   [For Feature, Post the link for design](https://jts.seagate.com/browse/CORTX-31365)
*   \[x] Side effects on other features (deployment/upgrade)
*   \[x] Dependencies on other component(s)
*   \[x] PR …
> Cortx 31365 version compatibility support from provisioner

- src/provisioner/const.py
- src/provisioner/provisioner.py
*   \[ ] JIRA number/GitHub Issue added to PR
*   \[ ] PR is self reviewed
*   \[ ] Jira and state/status is updated and JIRA is updated with PR link
*   \[ ] Check if the description is clear and explained
Checklist for …
> Cortx 31365 version compatibility

- src/provisioner/cluster.py
- src/provisioner/provisioner.py
- test/setup/test_provisioner.py
fix codacy dashboard issues
fix codacy dashboard issues
*   \[x] Jira and state/status is updated and JIRA is updated with PR link
*   \[x] Check if the description is clear and explained …
> CORTX-30259: fix codacy dashboard issues

- src/provisioner/provisioner.py
CORTX-31904 - Enhancements to access cortx gconf consul url at utils version compatibility check
hot fix for the provisioner changes which help to test component 
Signed-off-by: Zahid Shaikh <zahid.shaikh@seagate.com>
*   Enhancements to access cortx gconf consul url at utils version compatibility check
*   \[ ] …
> CORTX-31904 - Hot fix to consume consule-gconf url in provisioner code

- conf/gconf/cluster.conf.sample
- conf/solution/cluster.yaml.sample
- conf/solution/config.yaml.sample
Support for log devices in GCONF
*   \[x] Jira and state/status is updated and JIRA is updated with PR link
*   \[x] …
> CORTX-32810: add log devices in cortx conf files

- src/provisioner/provisioner.py
*   \[ ] JIRA number/GitHub Issue added to PR
*   \[ ] PR is self reviewed
*   \[ ] Jira and state/status is updated and JIRA is updated with PR link
*   \[ ] Check if …
> revert deployment time PR

- CODEOWNERS
*   \[ ] JIRA number/GitHub Issue added to PR
*   \[ ] PR is self reviewed
*   \[ ] Jira and state/status is updated and JIRA is updated with PR link
*   \[ ] Check if …
> remove kailashyadaw from codeowners list

- conf/gconf/cluster.conf.sample
- conf/solution/config.yaml.sample
- test/setup/config.yaml
*   update rgw gc parameters in gconf sample files
*   \[x] Jira and state/status is updated and JIRA is updated …
> CORTX-33499: update rgw gc parameters in gconf sample files
