Seagate/cortx-prvsnr

api/python/provisioner/commands/cmd_run.py
**cmd_run** provisioner API quoted parameters for **cortxcli**'s support_bundle command which invokes the **cortxcli** to read username and password from stdin. In general, **cortxcli** treats all parameters in double quotes as one-parameter and doesn't parse them accordingly.
Improve Provisioner API to support that **cortxcli** behavior.
=> [EOS-13685]: Fix double-quoting for cortxcli parameters

srv/components/ha/haproxy/files/haproxy.cfg
Signed-off-by: Ivan Tishchenko <ivan.tishchenko@seagate.com>
This addresses EOS-13717.  Issue there is: current implementation before the fix will do "floor division", and so maxconn calculated will be smaller than needed.  We have to have total at least 150 connections per node, and with floor division we're getting less than that (nmbproc=12, 150 // 12 = 12, so total = nbproc * maxconn = 12*12 = 144, less than 150).
So I'm changing this to do round-up division, which will give expected results.
=> EOS-13717: Round maxconn up instead of down in haproxy.cfg

cli/src/factory_ops/unboxing/config_update, cli/src/factory_ops/unboxing/init, srv/components/sspl/install.sls, srv/components/system/prepare.sls
Improvised fix to cleanup seagate specific URLs
1. Remove Seagate specific urls from commons and release pillars
2. Remove prepare salt state from components.sspl.install
3. Fix typos and improve logging.
=> EOS-13740: Remove seagate domain urls that gets generated as part of unboxing

Cortx-ProvisionerQuickstartGuide.md, api/python/provisioner/commands/configure_setup.py, api/python/provisioner/commands/get_setup_info.py, api/python/provisioner/config.py, api/python/provisioner/inputs.py, pillar/components/samples/generic_config.ini, pillar/components/samples/template.yml, pillar/components/storage_enclosure.sls
Change logic for storage_type detection. Use pillar based approach the first(values fills from user's **config.ini**). If it fails, use smart detection approach for that. Update **storage_enclosure/type** pillar value if it was missed originally.
=> [EOS-13675]: Rethink storage_type value detection method

srv/components/misc_pkgs/openldap/files/cfg_ldap.ldif
EOS-13836 ldap backend db mdb max size to be reduced to 10GB
Changes made in s3 and simillar changes needs to be done in provisioner cortx-1.0 
s3 PR : https://github.com/Seagate/cortx-s3server/pull/272/files
=> [LDR-R1]  EOS-13836 ldap backend db mdb max size to be reduced to 10GB

api/python/provisioner/srv/salt/firewall/init.sls
---------------------------------------------------------------
salt-ssh being used during bootstrap fails when network restarts
as a follow-up action for firewall config.
=> EOS-13072: Disable firewalld during bootstrap

srv/components/ha/haproxy/files/haproxy.cfg
Signed-off-by: Ivan Tishchenko <ivan.tishchenko@seagate.com>
=> EOS-13902: Add missing SSL CRT definition to bind :443

srv/components/ha/corosync-pacemaker/config/stonith.sls
JIRA: https://jts.seagate.com/browse/EOS-13330
Stonith resource stopping currently has no explicit timeout. According
to pcs man pages, by default stopping timeout is 20 seconds. The given
JIRA ticket showed 25 seconds of stopping and that made failover time
to happen too slowly.
Solution:
Set explicit timeout to 10 seconds
Signed-off-by: Konstantin Nekrasov <konstantin.nekrasov@seagate.com>
=> EOS-13330: stonith stopping can take >20s and thus slow down failover

srv/components/system/install.sls
Install ftp and sshpass packages as part of deployment, these packages are required for firmware update and support bundle feature.
=> Install ftp and sshpass

srv/components/system/install.sls
These packages are required for firmware update and support bundle feature.
=> Beta: Install ftp and sshpass packages as part of deployment

srv/components/ha/corosync-pacemaker/config/stonith.sls
JIRA: https://jts.seagate.com/browse/EOS-13330
Setting smaller timeout for STONITH resources was not quite justified.
If (by any reason) STONITH resource can't be stopped within the given
timeout, Pacemaker will fence the node. This will definitely not make
failover/failback to happen faster.
Solution: revert #595
=> EOS-13330: lower stop-timeout for STONITH is too dangerous

api/python/provisioner/commands/setup_provisioner.py, api/python/provisioner/utils.py
--------------------------------------------------------
EOS-14184: By-pass config.ini validation for replace_node
=> EOS-14184: By-pass config.ini validation

cli/src/factory_ops/boxing/init, cli/src/factory_ops/unboxing/init, cli/src/factory_ops/unboxing/pre_unbox, srv/components/system/config/sshd_boxing.sls
Added following fixes:
1. Add sleeps in between salt commands
2. Don't call function to prompt for controller IPs.
3. Don't disable root user.
This fix is because somehow minion wasn't able to get/lost the private ipaddrs in its grain data.
As discussed with @83bhp our private ip addr will be in static ip so we modified to fetch ipaddrs from cluster file.
The patch to fix the root user disablement is now fixed but it needs additional fixes, so disabling it until the fixes from Beta branch are ported.
=> Fixes in Boxing and Unboxing

srv/components/misc_pkgs/kibana/files/kibana.yml.j2
Kept default user and pass same as kibana.yml so that in diff it will not show password.
=> [EOS-14258] default username is user for kibana 

api/python/provisioner/commands/__init__.py, api/python/provisioner/commands/get_setup_info.py, api/python/provisioner/config.py, api/python/provisioner/inputs.py, srv/components/misc_pkgs/swupdate/repo/init.sls, srv/components/misc_pkgs/swupdate/repo/install.sls, srv/components/misc_pkgs/swupdate/repo/teardown.sls
- sets the framework for set commands dynamic validation
- implements logic of temporarily dynamic configuration for a new repo candidate to allow safe pre-checks before actual repo activation
=> [EOS-6078] adds base logic for sw update repo dynamic validation

srv/components/misc_pkgs/rabbitmq/config/base.sls, srv/components/misc_pkgs/rabbitmq/files/rabbitmq-server, srv/components/system/logrotate/files/etc/logrotate_hw.d/provisioner
Observed that another rabbitmq's conf file is getting created after rpm's installation at /etc/logrotate.d/ location.
So, Updating logrotate configuration in the default conf file instead of creating new conf file at /etc/logrotate_hourly.d/ location.
Also, did another improvement changes related to log rotate.
Signed-off-by: Vijay Thakkar <vijaykumar.thakkar@seagate.com>
=> Update default rabbitmq's conf file instead of creating new conf file

.github/workflows/triage.yml
Signed-off-by: Gaurav Chaudhari <gaurav.chaudhari@seagate.com>
Triage is an important part of open source. It can be difficult to keep up with the issues as the size of a project grows, the demands placed on the maintainers grow. This means they are forced to choose between spending enormous amounts of time reviewing each GitHub issue, only skimming over issues, or worse, ignoring issues.
Triage action can help an open-source project by labeling newly opened issues as `needs-triage`. So, maintainers could easily filter out all unattended/missed issues and label them appropriately in triage meetings. Now, it would be easy for a specific group of maintainers to filter out issues of their expertise/interest and start reviewing it in a timely manner.
=> [GitHub-Action]  Issue triage

srv/components/misc_pkgs/rabbitmq/config/base.sls
Tested with a custom build by applying components.misc_pkgs.rabbitmq
=> Enabling RabbitMQ cluster partition autoheal

srv/components/misc_pkgs/rabbitmq/config/base.sls
causing issue with comma as below new config was added. Reverting for now.
{cluster_nodes, {['rabbit@srvnode-1', 'rabbit@srvnode-2'], disc}}
=> reverting rabbit autoheal config

srv/components/controller/files/scripts/controller-cli.sh, srv/components/controller/files/scripts/provision.sh
Changes in this patch:
1. If for some reason the ftp session to controller gets stuck the session has to be killed after pre-defined timeout of 1 hour.
2. Remove echo statements which logs password (text) in log file.
=> EOS-14736: Timeout the ftp session with controller during firmware update

srv/components/ha/corosync-pacemaker/config/stonith.sls
This makes fence_ipmilan to log messages to system log about power
status.
Note: --debug-file option represented by debug_file option is more
appropriate here, however actual tests showed that it is working only
along with verbose option and does not prevent logging to syslog.
Also debug_file option does not pass validation and requires --force to
be applied when stonith resource is created. This looks fishy, thus
unreliable.
Signed-off-by: Andrei Zheregelia <andrei.zheregelia@seagate.com>
=> EOS-14658: add verbosity to stonith resources

srv/components/ha/corosync-pacemaker/config/stonith.sls
Solution: add failure-timeout=15s for both stonith resources so even
stonith resource fails to start (e.g. due to cable issue), in 15 seconds
Pacemaker will try to launch it again.
=> EOS-14924: when stonith is down, it will never come back online without manual intervention

cli/src/replace_node/deploy-replacement
=> EOS-14993:Serial number is lost when build info is fetched by CSM

cli/src/factory_ops/unboxing/init
Need to run CSM config state at the end of boxing as the system maintenance page of CSM shows the old hostnames.
Signed-off-by: root <root@ssc-vm-c-1394.colo.seagate.com>
Signed-off-by: root <root@ssc-vm-c-1394.colo.seagate.com>
=> EOS-14050: Run CSM config state at the end of unboxing.

api/python/provisioner/commands/setup_provisioner.py, api/python/provisioner/salt.py, cli/src/factory_ops/boxing/init, cli/src/factory_ops/boxing/prov_tasks, cli/src/factory_ops/unboxing/init, srv/components/system/config/init.sls, srv/components/system/config/service_user.sls
The logic:
- user is created at setup provisioner stage and the generated password is put into the pillar
- on the second node the account would be disabled (expired)
- during the deployment stage it should be encrypted
- at boxing time the credentials are dumped as before to log file so one can extract them for the docs
- (optionally) we may remove the password from pillar here if needed (one line change but I am not sure that we need that)
- at unboxing time the acoount on the secondary node is activated (expiration is set to 'never')
=> [EOS-15007] cortxub user configuration as a service user

api/python/provisioner/__main__.py, api/python/provisioner/__metadata__.py, api/python/provisioner/commands/__init__.py, api/python/provisioner/commands/_basic.py, api/python/provisioner/config.py, api/python/provisioner/paths.py, api/python/provisioner/pillar.py, api/python/provisioner/salt.py, api/python/provisioner/utils.py, api/python/setup.py, srv/components/provisioner/salt_master/files/master, srv/components/provisioner/salt_minion/files/minion
- provisioner `pillar_get` a `pillar_set` comands now supports `--local` option that will switch the mode to use `salt-call --local`
- also one more pillar root was added into account `/srv/glusterfs/volume_prvsnr_data/srv/pillar`
- it means that local mode would work for both read and write pillar requests even if salt and gluster services are not running:
- set commands will update values in `/var/lib/seagate/cortx/provisioner/local/srv/pillar` (it is not shared via gluster)
- get commands will take into account both gluster brick `/srv/glusterfs/volume_prvsnr_data/srv/pillar` and `/var/lib/seagate/cortx/provisioner/local/srv/pillar`
=> [EOS-14140] light pillar set/get using salt-call --local wrapper

cli/src/factory_ops/unboxing/network/bmc
=> EOS-15195: Incorrect IP printed for BMC during unboxing

cli/src/replace_node/deploy-replacement
-------------------------------------------------------
After node replacement, replaced node doesn't reflect updated version
update provisioner at deploy-replacement (#786)
Signed-off-by: Andrey Kononykhin <andrey.kononykhin@seagate.com>
Co-authored-by: Yashodhan Pise <yashodhan.pise@seagate.com>
fixes identified issue (#794)
Signed-off-by: Andrey Kononykhin <andrey.kononykhin@seagate.com>
=> EOS-15403: Replaced node doesn't reflect updated version

pillar/components/csm.sls, pillar/top.sls
Autogenerate password for csm user at the time of deployment.
A blank pillar entry with key secret/password is assigned a dynamically generated password string during deployment as its value.
=> EOS-15665: Generate passwd for csm user

api/python/provisioner/__main__.py, api/python/provisioner/_api.py, api/python/provisioner/api_spec.yaml, api/python/provisioner/cli_parser.py, api/python/provisioner/commands/_basic.py, api/python/provisioner/commands/check.py, api/python/provisioner/commands/salt.py, api/python/provisioner/config.py, api/python/provisioner/fileroot.py, api/python/provisioner/inputs.py, api/python/provisioner/paths.py, api/python/provisioner/pillar.py, api/python/provisioner/runner.py, api/python/provisioner/salt.py, api/python/provisioner/salt_api/__init__.py, api/python/provisioner/salt_api/auth.py, api/python/provisioner/salt_api/base.py, api/python/provisioner/salt_api/caller.py, api/python/provisioner/salt_api/client.py, api/python/provisioner/salt_api/runner.py, api/python/provisioner/salt_api/ssh.py
New provisioenr API command-wrapper over different salt client. Available as both python API and CLI.                                                                                                                                        
General goals:                                                                                                                                                                                                                               
- provide generic API over salt's ones
- make salt-ssh based operation as simple as others
**As CLI**
`provisioner salt CLIENT FUN [--fun-args ARG ...] [--fun-kwargs ARG=VALUE ...]`
where 
- `CLIENT` is one of {salt|runner|caller|local|ssh}
- `FUN` is a Salt's fun (e.g. `test.ping`, `state.apply`, `jobs.list_jobs` ...) …
=> [EOS-15022][part 1] improves salt wrapper abstractions

cli/src/replace_node/deploy-replacement
Signed-off-by: Anjali Somwanshi anjali.somwanshi@seagate.com
=> EOS-14767-sms2: System maintenance page throws error "service status can't be checked as services are restarting"

srv/components/ha/corosync-pacemaker/config/stonith.sls
Signed-off-by: ajay.paratmandali@seagate.com <ajay.paratmandali@seagate.com>
Fixes #
Increases delay for stonith-c1 to avoid both node shutdown.
Bug: EOS-15821
=> Update stonith configuration with delay 20

cli/src/destroy, cli/src/destroy-vm, srv/components/ha/corosync-pacemaker/teardown.sls, srv/components/ha/cortx-ha/ha_cleanup.sls
1.  In R1 we had ctrlstack-ha , iostack-ha and cortx-ha but in R2 we have only cortx-ha which will take care of complete pcs cluster.
2.  In R2 we have mini provisioner available at cortx-ha component to cleanup pcs cluster. provisioner need to call mini provisioner to cleanup.
=> [EOS-17445] destroy ha components on single node vm

api/python/provisioner/commands/deploy_vm.py
starting cortx-cluster:
`cortx cluster start`
will run by either from GUI or admin will run it.
=> [EOS-17836] Bootstrap cluster should not be part of provisioner

srv/components/provisioner/files/cluster_sls.template, srv/components/system/config/hosts.sls
Addresses:
- Define internal custom domains for data/mgmt interfaces
- Network Config update for existing cluster (FQDN support)
=> EOS-17569, EOS-17821: Network Config update for existing cluster (FQDN support)

api/python/provisioner/commands/setup_provisioner.py, api/python/provisioner/salt.py, api/python/provisioner/srv/salt/cortx_repos/install.sls, api/python/setup.py, files/etc/yum.repos.d/saltstack.repo, srv/components/provisioner/config/init.sls, test/build_helpers/__init__.py, test/build_helpers/conftest.py, test/build_helpers/test_build_env.py, test/conftest.py, test/helper.py
Summary:
- adds ability to setup testing env of multiple nodes using pytest testing scenario
- makes setup provisioner logic more flexible for `local` source
Example of usage:
- install docker
- run `pytest test/build_helpers -k test_build_setup_env -s --root-passwd root1 --nodes-num 3`
- that will start (almost) clean docker containers and configure root passwords as specified
- print ssh configuration for the prepared env into the output
- then it would prompt for a key (once any key is pressed it would teardown the env)
- possible options (you may check them using `pytest test/build_helpers --help`, `custom options` part)
- `--docker-mount-dev` to mount `/dev` into containers (necessary if you need to mount ISO inside a container)
- `--root-passwd <STR>` to set a root password for …
=> Test helpers for setup routine

devops/rpms/buildrpm.sh, devops/rpms/cortx-prvsnr.spec, srv/components/provisioner/salt_master/files/master, srv/components/provisioner/salt_minion/files/minion
I added `api/python/provisioner/srv/salt/repos` to core provisioner rpm package to use for sw upgrade
=> EOS-18337: Make bootstrap API salt states for cortx repositories available in deployed environment

api/python/provisioner/commands/setup_provisioner.py
Signed-off-by: mazinamdar mazhar.inamdar@seagate.com
Grains data is not getting refreshed within sls files if we call init.sls for machine_id states.
so applied states separately.
=> [EOS-18405] Integrate refresh machine_id states with setup provisioner API

srv/components/provisioner/config/machine_id/refresh_grains.sls
Even if we refresh grains data mine data is not getting refreshed so added mine.update after that mine is getting updated
=> update mine data after machine_id refresh

api/python/provisioner/srv/salt/provisioner/api/install.sls, docs/testing.md
I added the setup of the `LC_ALL` variable during the pip installation of provisioner dependencies.
-----
[View rendered docs/testing.md](https://github.com/Seagate/cortx-prvsnr/blob/EOS-18457/docs/testing.md)
=> EOS-18457: Filename encoding error in PIP environment

api/python/provisioner/commands/deploy.py, api/python/provisioner/commands/deploy_vm.py, srv/components/system/firewall/init.sls
Issue is it is trying to resolve all jinja template first so at initial level we don't have any zones created but in sanity jinja we are trying to fetch all zones that's why it is failing.
```
To apply the state, Salt needs to convert it from YAML format to a data structure. Since it is impossible to parse a YAML file that has Jinja statements inside, Salt needs to parse Jinja first.
In other words, the pipeline looks like this:
Parse Jinja
Parse the resulting YAML
Interpret the data structure
Apply the state```
=> [HOTFIX] Fix firewall sanity issue

api/python/provisioner/api_spec.yaml, api/python/provisioner/cli_parser.py, api/python/provisioner/commands/_basic.py, api/python/provisioner/commands/helper.py, api/python/provisioner/commands/resource.py, api/python/provisioner/commands/salt.py, api/python/provisioner/commands/set_swupgrade_repo.py, api/python/provisioner/commands/setup_provisioner.py, api/python/provisioner/config.py, api/python/provisioner/discovery.py, api/python/provisioner/fileroot.py, api/python/provisioner/inputs.py, api/python/provisioner/log.py, api/python/provisioner/node.py, api/python/provisioner/pillar.py, api/python/provisioner/profile.py, api/python/provisioner/resources/__init__.py, api/python/provisioner/resources/base.py, api/python/provisioner/resources/cortx_repos.py, api/python/provisioner/salt_api/base.py, api/python/provisioner/salt_api/ssh.py, api/python/provisioner/scm/__init__.py, api/python/provisioner/scm/saltstack/__init__.py, api/python/provisioner/scm/saltstack/rc_sls/__init__.py, api/python/provisioner/scm/saltstack/rc_sls/base.py, api/python/provisioner/scm/saltstack/rc_sls/cortx_repos.py, api/python/provisioner/srv/salt/_modules/prvsnr.py, api/python/provisioner/srv/salt/repos/_macros.sls, api/python/provisioner/srv/salt/resources/misc/repos, api/python/provisioner/utils.py
The PR introduces a new design of integration between provisioner API and salt states based on understanding of resources.
The changes include implementation of the base abstractions
- `ResourceBase`
- `ResourceParams`
- `ResourceState`
- `ResourceTransition`
- `ResourceManagerBase`
... along with specific implementation for cortx repositories resource:
- `CortxRepos`
- `CortxReposSetup`
- `CortxReposParams`
... and SaltStack as a resource manager:
- `SLSResourceManager`
-  `CortxReposSetupSLS`
Also the change introduces the following CLI commands:
- `provisioner helper` a group of helper commands, in particular
- `provisioner helper generate-profile` to generate ssh profile when salt-ssh is run in a custom env (e.g. at bootstrap)
- `provisioner helper ensure-nodes-ready` to ensure that …
=> [EOS-17600] adds basis of the new modular logic and repos support

api/python/provisioner/inputs.py, devops/rpms/buildrpm.sh, devops/rpms/cortx-prvsnr.spec, docs/mocks.md, docs/testing.md, images/docker/setup_fpm.sh, srv/components/misc_pkgs/mocks/cortx/files/scripts/buildbundle.sh, test/build_helpers/build_bundles/conftest.py, test/build_helpers/build_bundles/test_build_bundles.py, test/build_helpers/build_env/conftest.py, test/build_helpers/build_prvsnr_pkgs/__init__.py, test/build_helpers/build_prvsnr_pkgs/conftest.py, test/build_helpers/build_prvsnr_pkgs/test_build_prvsnr_pkgs.py, test/build_helpers/conftest.py, test/conftest.py, test/helper.py
Improves test helpers:
- (new) `pytest test/build_helpers/build_prvsnr_pkgs` to build provisioner packages in docker
- (improved) `pytest test/build_helpers/build_bundles` to build Cortx bundles in docker, changes:
- improves command line args support
- extends list of them to allow passing paths to provisioner packages so they would be packed inside a bundle (if not passed then ones from original single iso wouldbe used if the it is providede)
Please check updated docs for more details and examples.
-----
[View rendered docs/mocks.md](https://github.com/andkononykhin2/cortx-prvsnr/blob/pack-provisioner-pkgs-into-bundles/docs/mocks.md)
[View rendered docs/testing.md](https://github.com/andkononykhin2/cortx-prvsnr/blob/pack-provisioner-pkgs-into-bundles/docs/testing.md)
=> [testing][mocks] Pack provisioner pkgs into bundles

pillar/components/firewall.sls
[Firewall-Ports-R2](https://seagatetechnology.sharepoint.com/:x:/s/gteamdrv1/tdrive1224/EZRT8UanK0RNi35n8a6uplQBLL-WmNhfjaXElJ7Iq70u2Q?e=tlNe7H) 
Strictly followed this list for open ports and tested on 3-node cluster. 
Removed all Private and Internal network ports and kept only incoming ports and data-public and mgmt-public ports. 
Apart from the list, only retained the initial default services ssh, salt (incoming) and glusterfs (not mentioned in sheet) as such.
=> EOS-17828: firewall ports adjustments

srv/components/ha/haproxy/files/haproxy.cfg, srv/components/ha/haproxy/init.sls, srv/components/provisioner/files/setup.yaml
Such configuration has been introduced with https://github.com/Seagate/cortx-prvsnr/pull/868/commits/17a9c556717b0dc65087e8458eb94891ba1d72f8.
Because HAproxy binds to *:5000, UDS cannot bind to port 5000 and hence CSM cannot reach its server.
=> EOS-19102: Erroneous HAproxy configuration

api/python/provisioner/api_spec.yaml, api/python/provisioner/commands/configure_node.py
Used subprocess to call TUI script as salt_cmd is not working in this case.
`
provisioner configure_node
`
=> [EOS-19135] Provisioner CLI to trigger northbound TUI

docs/Architecture/SW-Upgrade.md, test/r2.md
I committed the initial version of architecture docs for SW upgrade. I updated also the testing docs for SW upgrade testing
=> EOS-15752: Document API for SW upgrade release bundle setup/teardown

EOS-19173.patch, api/python/provisioner/commands/__init__.py
The PR has follwing changes:
'cortx-sspl-test' added in exclude rpms within GetReleaseVersion
=> [EOS-19173] build 607 - Update - Release Version is Still shown as 1.0

api/python/provisioner/commands/destroy.py, srv/components/hare/teardown.sls
1. hctl cluster start / shutdown is not part of hare.
2. Improve error logging
=> [EOS-19218] Remove hctl cluster shutdown from hare

srv/components/system/config/set_hostname.sls
hostname was getting reset to old one on reboot due to "operation not permitted" error
fix:
1. Remove `i` attribute from /etc/hostname 
2. Use hostnamectl command to set the hostname
=> EOS-19490: Fix - hostname reset on reboot

srv/components/system/storage/config.sls
1. Set priority for both primary and secondary swap spaces
2. Enable swap using `mount.swapon` instead of `mount.swap` which was setting priority
=> EOS-19654-Fix: swap spaces on LR R1 systems have incorrect priority

api/python/provisioner/srv/salt/provisioner/files/post_setup.sh
Grant `prvsnrusers` group a access to `/var/lib/seagate/cortx/provisioner/shared/locks` directory
=> EOS-19735: File for SW update is not getting uploaded

api/python/provisioner/commands/destroy.py, srv/components/motr/teardown/cleanup.sls, srv/components/provisioner/teardown/package_remove.sls, srv/components/sspl/teardown/init.sls, srv/components/system/storage/glusterfs/teardown/cache_remove.sls
1. python36-m2crypto is removing salt packages because of which other steps are getting skip.
2. Removed conflicting of ID's in Motr teardown 
3. No need to call sspl.teardown.common as we are not adding anything in consul during deployment.
4. Fixed syntax of cache_remove from gluster.teardown
FYI: We have  not seen firewall issue ( 2hrs ) locally it is seen only in case of jenkins job.
=> [Fix] Fixes destroy API for 3 node

srv/components/system/config/set_hostname.sls
Run `set-hostname` command using `cmd.run` module since `network.system` has below issue currently
https://github.com/saltstack/salt/issues/59973
=> EOS-19816: hostname updates twice in /etc/sysconfig/network

srv/components/system/network/data/direct/init.sls
Currently we are using `private_interfaces[1]` for private_data configuration but it will fail if only one interface is present in `cluster:node_id:data_private_interfaces` 
to fix this issue, updated `private_interfaces[0]` for private data network configuration 
=> EOS-19815: Update eth3 as part of private data network configuration

api/python/provisioner/commands/deploy.py, api/python/provisioner/commands/deploy_vm.py, api/python/provisioner/commands/destroy.py, api/python/provisioner/srv/salt/ssh/check.sls, api/python/provisioner/srv/salt/ssh/files/config, api/python/provisioner/utils.py
1. Change deployment sequence for cortx-ha:
First deploy on Primary then on secondaries in a set.
2. Add private fqdns in passwordless ssh configuration
3. Remove "(" & ")" chars from set of special chars for
random password generation module.
=> EOS-19834: Fix issues for Cortx-ha deployment for 3 node

srv/components/misc_pkgs/elasticsearch/teardown.sls
=> EOS-19470: Remove Opendistro rpm used for elasticsearch and kibana deployment

api/python/provisioner/commands/deploy.py, api/python/provisioner/commands/destroy.py
1. Move the dead code of validation check for consul before running
cortx-ha component.
2. Fix typo in destroy - change rabbitmq to rabbitmq.teardown
=> Fix minor issues in deploy and destroy.

srv/components/uds/teardown.sls
=> EOS-20627:destroy api does not remove uds packages

api/python/provisioner/commands/destroy.py
removed unwanted cache logs during destroy API
=> Hide unwanted cache logs from salt-ssh

lr-cli/cortx_setup/commands/network/config.py, lr-cli/cortx_setup/commands/node/prepare/network.py
1. Updated --type argument to support `private` network
2. Used --mode argument instead of `transport_type` and `interface_type` arguments
3. Renamed `mgmt` input value to `management`
=> Improvement - Network configuration and prepare

srv/components/misc_pkgs/kafka/files/zookeeper.properties, srv/components/misc_pkgs/kafka/start.sls, srv/components/misc_pkgs/kafka/stop.sls
-----------------------------------------------------------------------------------------
Change ensure Zookeeper response is checked before proceeding to start Kafka service
```
ID: Ensure kafka-zookeeper is responsive for srvnode-1
Function: cmd.run
Name: echo ruok|nc srvnode-1 2181|grep imok
Result: True
Comment: Attempt 1: Returned a result of "False", with the following comment: "Command "echo ruok|nc srvnode-1 2181|grep imok" run"
Command "echo ruok|nc srvnode-1 2181|grep imok" run
Started: 18:17:02.101428
Duration: 10062.195 ms
Changes:
----------
pid:
30861
retcode:
0
stderr:
stdout:
imok
```
=> EOS-20863: Ensure response from Zookeeper before starting Kafka

lr-cli/cortx_setup/commands/storage/commons.py
=> EOS-21181: cortx_setup command fails to set enclosure_id

pillar/components/execution.sls, pillar/components/firewall.sls, pillar/components/glusterfs.sls, srv/components/system/firewall/config.sls, srv/components/system/firewall/teardown.sls
--------------------------------------------------------------------------------
This PR adds control in firewall for private data network.
The whole section (data_private) in pillar sls file is optional. Same applies to input yaml to `lr_cli` command.
If added, it creates a dedicated zone: private-data-zone for the private data network NICs.
If skipped, it adds the private data network NICs to the trusted zone.
=> EOS-21344, EOS-19911: Configure firewall settings

lr-cli/cortx_setup/api_spec.yaml, lr-cli/cortx_setup/commands/__init__.py, lr-cli/cortx_setup/commands/cluster/config/component.py, lr-cli/cortx_setup/commands/cluster/prepare.py, pillar/components/execution.sls
Addressed:
1. Rename `cortx_setup node prepare` to `cortx_setup cluster prepare`
2. Remove `ha`  component from `cortx_setup node initialize` and `cortx_setup cluster prepare` and apply in `cortx_setup cluster config`
=> Fix: cluster config and prepare commands

lr-cli/cortx_setup/commands/resource/discover.py, lr-cli/cortx_setup/commands/resource/show.py, lr-cli/cortx_setup/commands/storage/config.py, srv/components/system/config/hosts.sls
This PR has fixes for -
1. enclosure password encryption into confstore was using wrong key. should have been 'storage_enclosure' instead of 'storage'
2. not parsing request id received from resource discovery
3. removing srvnode-1 mapping in etc hosts with public data ip
=> Fixes related to resource discover and show api

api/python/provisioner/commands/release/get_release.py, api/python/provisioner/config.py
1. support target parameter in get_release_version API (EOS-22032)
2. Fix get_release_version API which causing issue's to get_iso_version API.
=> [EOS-22098][EOS-22032]: Fix get release version API for R2

srv/components/ha/haproxy/config.sls, srv/components/ha/haproxy/start.sls, srv/components/ha/haproxy/teardown.sls, srv/components/misc_pkgs/kibana/start.sls
Addressed:
- Do not update haproxy.service in provisioner. i.e remove override.conf 
- Do not enable haproxy.service
- Do not enable kibana.service
=> EOS-21915: Provisioner: Discrepancy in systemd resources

api/python/provisioner/inputs.py, api/python/provisioner/params_spec.yaml, lr-cli/cortx_setup/commands/node/prepare/network.py, srv/components/system/network/data/direct/init.sls
Fixed below network configurations:
1. Remove statically added prefix value from srv/components/system/network/data/direct.sls
2. Update `netmask` and `gateway` for private_data network.
=> fix network configuration issues with prefix

lr-cli/cortx_setup/commands/node/prepare/network.py, srv/components/system/network/resolv_conf.sls
Tested with following command:
cortx_setup node prepare network --dns_servers 10.230.240.51 10.230.240.52  --search_domains colo.seagate.com eos.colo.seagate.com cortx.colo.seagate.com
=> EOS-22276: adding dns server and search domain in node prepare network

api/python/provisioner/commands/upgrade/sw_upgrade.py, api/python/provisioner/cortx_ha.py
=> EOS-22119: Use cluster_manager start api instead of unstandby

node_cli/__init__.py, node_cli/client.py, node_cli/config.py, node_cli/nodecli.py, node_cli/schema/cluster.json, node_cli/schema/node.json
To run nodecli in dev mode:
``` 
checkout cortx-prvsnr code
cp -r node_cli  /opt/seagate/cortx/provisioner/
export PYTHONPATH='/opt/seagate/cortx/provisioner/' 
python3 /opt/seagate/cortx/provisioner/node_cli/nodecli.py
```
Sample nodecli commands:
```
node prepare network --hostname ssc-vm-rhev4-0315.colo.seagate.com
cluster show
```
=> [EOS-19899] : Node cli framework for captive CLI

lr-cli/cortx_setup/commands/resource/show.py
=> EOS-23002: Node Health - Resource health status is coming as 'NA' for 'inactive' services and other resources

api/python/provisioner/commands/bootstrap_provisioner.py, api/python/provisioner/inputs.py, lr-cli/cortx_setup/commands/cluster/create.py, lr-cli/cortx_setup/commands/cluster/encrypt.py, lr-cli/cortx_setup/commands/cluster/generate.py
Addressed:
1. Use current user for field deployment
2. setup_provisioner command failure
=> EOS-23507: Use current user for field deployment

api/python/provisioner/commands/setup_provisioner.py
EOS-23534: use uuid as name of profile directory in setup_provisioner
=> EOS-23534: use uuid as name of profile directory in setup_provisioner

lr-cli/cortx_setup/commands/storageset/add/enclosure.py, lr-cli/cortx_setup/commands/storageset/add/node.py, lr-cli/cortx_setup/commands/storageset/config/durability.py, lr-cli/cortx_setup/commands/storageset/create.py, srv/components/provisioner/files/cluster_sls.template, srv/components/system/files/confstore_template.j2
* EOS-23606: Support to add more than 3 nodes in one storage set
* EOS-23606: add storage set details in confstore, remove hardcoding.
* EOS-23606: fix bugs found in testing.
* EOS-23606: Fix bugs
* EOS-23606: Address Codacy issues.
* EOS-23606: address review comment
* EOS-23606: Handle exception gracefully
* EOS-23606: Addressed code reivew changes.
Signed-off-by: Pritam Bhavsar …
=> EOS-23606: Add support to add more than 3 nodes in storage set (#6086)

test/deploy/k8s/cluster.yaml, test/deploy/k8s/cortx-statefulset.yml, test/deploy/k8s/deploy.sh, test/deploy/k8s/destroy.sh
- Add machine-id to each POD in Kubernetes cluster
- as part of the config-map we provide a cluster.yaml file to POD's which has all pod's data. In this PR, using statefulset we are creating pods to have unique names (podnode-0,podnode-1..podnode-n) . and this unique name will be mapped to the pod name from cluster.yaml file and from cluster.yaml will fetch the id and place it inside etc/machine-id file.
=> EOS-24770: Add machne-id to each POD in kubernetes cluster

api/python/provisioner/commands/bootstrap_provisioner.py, api/python/provisioner/srv/salt/provisioner/configure_salt_master.sls, pillar/components/firewall.sls, srv/components/provisioner/salt_master/config.sls, srv/components/provisioner/salt_master/files/master_factory, srv/components/provisioner/scripts/install.sh, srv/components/system/firewall/files/firewall_config.yaml
Fix following issues:
EOS-24654: Create glob for target minions instead of string of concatenated minion ids
EOS-23433: Firewall configuration updated with all services and ports
EOS-24654: Use hostname to update master in minion to address 1N deployment failures.
-  Opened only the required ports in private zone of firewall.
- Moved Salt ports to management zone
=> Fixes for Main candidate 

experiments/logging/glusterfs/Dockerfile, experiments/logging/glusterfs/README.md, experiments/logging/glusterfs/glusterfs-pv.yml, experiments/logging/glusterfs/glusterfs-pvc.yml, experiments/logging/glusterfs/log.py, experiments/logging/glusterfs/pod.yml
- Add pv, pvc and pod spec file
- Add readme
Signed-off-by: Sandeep Anjara <sandeep.anjara@seagate.com>
- Demonstrate logging on top of glusterfs volume
-  NA
-----
[View rendered experiments/logging/README.md](https://github.com/sandeepsgt/cortx-prvsnr/blob/EOS-24087/experiments/logging/glusterfs/README.md)
=> EOS-24087: Add K8S example files for logging

src/setup/cortx_deploy, src/setup/cortx_setup.py
- Change Confstore URL Argument to -c to make it consistent accross the workflow.
=> EOS-24455: changed confstore file URL argument for cortx_setup command to -c

src/provisioner/const.py, src/provisioner/log.py, src/provisioner/provisioner.py, src/setup/cortx_setup.py
Ensure provisioner logs are writing in configured log path (Kubernete, local VM env)
As part of this, we identified that ConfigStore will not be available to provisioner config apply command. To overcome this, let write the config apply log information in tmp file. Once ConfigStore is ready with log location, initialize the logger and append tmp logs to required log path file.
=> EOS-24981: Test component logging - Provisioner

test/deploy/kubernetes/provisioner-pods/deployment_control_node.yaml, test/deploy/kubernetes/provisioner-pods/deployment_storage_node1.yaml, test/deploy/kubernetes/provisioner-pods/deployment_storage_node2.yaml, test/deploy/kubernetes/provisioner-pods/deployment_storage_node3.yaml
…amework
- EOS-24455: Remove Privilaged mode from Provisioner kubernetes test framework
=> EOS-24455: Remove Privilaged mode from Provisioner kubernetes test framework

src/provisioner/const.py, src/provisioner/log.py, src/provisioner/provisioner.py
Provisioner writes cortx_setup.log under,
/share/var/log/cortx/<machine-id>/provisioner/
All other components are following like,
/share/var/log/cortx/<component>/<machine-id>/
So provisioner also has to follow the same.
=> EOS-25205: Change in provisioner log path structure

src/setup/cortx_deploy, test/deploy/kubernetes/provisioner-pods/deployment_control_node.yaml, test/deploy/kubernetes/provisioner-pods/deployment_storage_node1.yaml, test/deploy/kubernetes/provisioner-pods/deployment_storage_node2.yaml, test/deploy/kubernetes/provisioner-pods/deployment_storage_node3.yaml, test/deploy/kubernetes/reimage.sh, test/deploy/kubernetes/template-config/cluster_redefined.yaml, test/deploy/kubernetes/upgrade-pods/upgrade_control_node.yaml, test/deploy/kubernetes/upgrade-pods/upgrade_data_node1.yaml, test/deploy/kubernetes/upgrade-pods/upgrade_data_node2.yaml, test/deploy/kubernetes/upgrade-pods/upgrade_data_node3.yaml, test/deploy/kubernetes/upgrade-pods/upgrade_ha_node.yaml, test/deploy/kubernetes/upgrade-pods/upgrade_server_node1.yaml, test/deploy/kubernetes/upgrade-pods/upgrade_server_node2.yaml, test/deploy/kubernetes/upgrade-pods/upgrade_server_node3.yaml, test/deploy/kubernetes/upgrade-pods/upgrade_storage_node1.yaml, test/deploy/kubernetes/upgrade-pods/upgrade_storage_node2.yaml, test/deploy/kubernetes/upgrade-pods/upgrade_storage_node3.yaml, test/deploy/kubernetes/upgrade.sh
- remove mock for deployment pods
- call provisioner entry point in upgrade pods
- rename storage-node with data-node in redefined_cluster.yaml
- PID implementation for upgrade script to avoid parallel upgrade.
=> added few modifications for upgrade script for avoiding parrallel upgrade as well as few improvments

src/provisioner/provisioner.py, test/deploy/kubernetes/upgrade.sh
- In case of system crash/pod restarts, Provisioning phase status will be in 'progress'. 
- If status=progress detected, reset status to default and start upgrade/deployment again.
- Before calling upgrading interface for component, added component version check.
=> Changed validation for 'in-progress' provisioning state.

conf/config.yaml.sample, test/deploy/kubernetes/solution-config/config.yaml
Adding new consul endpoint into config.yaml
https://jts.seagate.com/browse/EOS-26741
Add another endpoint into list of endpoints for consul, as consul is not reachable for 8301 port.
New endpoint will be pointing to 8500 and with http protocol
=> Adding new consul endpoint into config.yaml

test/deploy/kubernetes/template-config/cluster_redefined.yaml
- Update data_node type as storage_node in redefined pods flow
-  [For Bug, Describe the fix here.](https://jts.seagate.com/browse/EOS-26800)
- Hare mini provisioner failing for redefined pods flow because of node type has been changed to data_node from storage_node. Temporarily reverting node_type to storage_node.
=> EOS-26800: Update data_node type as storage_node in redefined pods flow

test/deploy/kubernetes/template-config/cluster_redefined.yaml
-EOS-26800: revert storage_node to data_node in cluster redefined pods
=> EOS-26800: revert storage_node to data_node in cluster redefined pods

conf/solution/cluster.yaml.sample, src/provisioner/cluster.py, src/provisioner/config.py, src/provisioner/const.py, src/provisioner/provisioner.py
- Add code for setting num keys to the gconf arrays
- remove code for previous counter keys
-  https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/651132980/CORTX+GConf+Config+Store+Keys
=> Eos 27645 num array improvements to gconf 

src/provisioner/cluster.py, src/provisioner/provisioner.py
- In the config apply stage of the provisioner , we add a version field for all components by searching all component rpms in the RELEASE.INFO file. so even if it's a data pod or any other pod, we search all components to add versions in it and not only data pod components. so for granular images, if other component RPMs are missing, the provisioner throws an error saying "rpm for csm not found".
-  Fix For above solution would be:
1. Remove add version for component from config apply state.
2. add version only after mini provisioning for the component is successful. This way only for that particular component utils will return version.
Checklist for …
=> EOS-28599: Update version for each component in bootstrap phase

jenkins/docker/python_requirements.ext.txt
Signed-off-by: Swanand S Gadre <swanand.s.gadre@seagate.com>
Current python version in all cortx pods is at python 3.6.8. All the versions of numpy above 1.19.X (i.e. 1.20.X, 1.21.X, 1.22.X) are not available for python 3.6.8.
Infact they are available from python 3.7.X ot 3.8.X onwards. So unless python version is not upgraded, numpy cannot be upgraded to the next version.
So plan is to upgrade numpy to latest minor version of 1.19.5. This upgrade will not fix any existing vulnerabilities, but from compliance perspective, it will take numpy to latest minor version compatible with cortx – python version.
https://jts.seagate.com/browse/CORTX-28927
-  [X] Coding conventions …
=> CORTX-28927 - upgrade package numpy from 1.19.XX to 1.19.5

src/provisioner/provisioner.py
- Missing num_data & num_metadata keys in cluster.conf
cvg:
- devices:
data:
- /dev/sdd
- /dev/sde
metadata:
- /dev/sdc
name: cvg-01
type: ios
Expected num keys for data & metadata (wherever applicable)
cvg:
- devices:
data:
num_data: 2
- /dev/sdd
- /dev/sde
metadata:
num_metadata: 1
- /dev/sdc
name: cvg-01
type: ios
-  https://jts.seagate.com/browse/CORTX-29052
=> CORTX-29052: fix: added function call for num_array keys

jenkins/docker/python_requirements.txt, srv/components/system/files/cortx_py_utils_requirements.txt
Upgrade aiohttp version from 3.6.1 to 3.8.1
This upgrade is expected to resolve security vulnerabilities.
This fix require changes in python_requirement.txt file to upgrade library version from 3.6.1 to 3.8.1
Corresponding story is - https://jts.seagate.com/browse/CORTX-27923
-  [X] Coding conventions are followed and code is consistent
All the test details are documented. Corresponding document is attached to -> https://jts.seagate.com/browse/CORTX-27923
No documentation updates
=> CORTX-27923 - Upgrade aiohttp from version 3.6.1 to 3.8.1

src/provisioner/cluster.py, src/provisioner/provisioner.py
*   Update generated cluster configuration at provisioning time with node_group set to Kubernetes worker node name
As part of [CORTX-29695](https://jts.seagate.com/browse/CORTX-29695), the node_group information will be injected at deployment time and available when the initContainer is running the provisioning logic. The cortx-k8s code will inject the Kubernetes worker node name into the initContainer as an environment variable (NODE_NAME) and the Provisioner logic will need to update the generated configuration information to set `node_group` to the value defined in NODE_NAME environment variable.
*   \[x] Test Cases cover Happy Path, …
=> CORTX-31277: add node_group for data nodes in gconf

jenkins/docker/python_requirements.txt
Signed-off-by: swanand-gadre <swanand.s.gadre@seagate.com>
Paramiko package 2.7.X is vulnerable.
It needs to be upgraded to version 2.10.4
This PR is raised to upgrade this version.
This PR is raised to upgrade paramiko package from 2.7.X to 2.10.4
*   \[X] Coding conventions are followed and code is consistent
*   \[X] Unit and System Tests are added
*   \[X] Test Cases cover Happy Path, Non-Happy Path and Scalability
*   \[X] Testing was performed with RPM
All test details are available in a document attached to this ticket -> https://jts.seagate.com/browse/CORTX-30265
*   \[ ] Interface change (if any) are …
=> CORTX-30265 - paramiko upgrade to 2.10.4

conf/solution/config.yaml.sample, src/provisioner/const.py, src/provisioner/provisioner.py, src/setup/cortx_deploy, test/setup/cluster.yaml, test/setup/config.yaml, test/setup/test_provisioner.py
Implement GCONF Upgrade, In a way that before calling upgrade mini provisioner of components, prepare a delta diff which will be passed to component miniprovisioner as part of cortx upgrade.
gconf should be only updated once all component mini provisioning is done.
*  Implement pre_upgrade and post_upgrade interfaces in provisioner which will handle gconf upgrade
*   \[ ] Side effects on …
=> CORTX-31132: Implementation for gconf upgrade

src/provisioner/cluster.py
*  Remove Const.data_node from provisioner
Data_node type values are prone to change with respect to multiple data pods, hence we need to remove the hard dependency from this constants and recognize data pods based on storage key.
*   \[x] JIRA number/GitHub Issue …
=> CORTX-32413: remove const.data_node from cluster.py

src/provisioner/provisioner.py
CORTX-32710: add deployment_time field in gconf priovisioner
Deployment time in epoch format needs to be added for each node once mini provisioning is successful.
*   \[x] Jira and state/status …
=> CORTX-32710: add deployment_time field in gconf priovisioner

src/provisioner/const.py, src/provisioner/provisioner.py, test/setup/test_provisioner.py
Provisioner needs to update the gconf creation logic for migrating to consul by implementing lock-unlock mechanism.
Workflow to be followed for lock-unlock mechanism:
def apply_config():
// config apply code    
def wait_for_lock_to_be_released(timeout):
while timeout > 0:
if not Conf.test_lock():
return True
time.sleep(1)
timeout -= 1
return False      
if not wait_for_lock_to_be_released(timeout):
conf.unlock(Force = True)
if conf.get(index, 'cortx>id') is None:
conf.lock()
conf.apply_config
conf.unlock()
*   \[x] …
=> CORTX-33648: lock unlock implementation for migrating config generation to consul

src/provisioner/provisioner.py
*   add deployment time field in gconf, which will add epoch time in 'node> <node-id> > proviosioner > time' field
* …
=> CORTX-33763: add deployment time in gconf

src/provisioner/provisioner.py
CORTX-33855: remove extra arrow from update provisioning status
*   \[x] Side effects on other features (deployment/upgrade)
*   \[x] Dependencies on other component(s)
*   \[x] Jira and state/status is updated and JIRA …
=> CORTX-33855: remove extra arrow from update provisioning status

src/provisioner/provisioner.py
*   CORTX-33673: update lock unlock parameters with new improvment changes
*   Update lock unlock interface call parameters as per changes in utils locking framework.
*   \[x] Dependencies on other component(s)
*   \[x] Jira and …
=> CORTX-33673: update lock unlock parameters with new improvment changes

test/setup/test_setup.py
Signed-off-by: Lakshita Jain <lakshita.jain@seagate.com>
*   fix the existing Unit Tests in Provisioner
*   add cortx_setup module in imports
*   \[x] Jira and state/status is updated and JIRA is updated with …
=> CORTX-32832: fixing unit tests in test_setup
